\if :{?result_file}
\else
\set result_file artifacts/rbac01-db-audit/RBAC01_DB_AUDIT_RESULTS_manual.txt
\endif
\if :{?roles_csv}
\else
\set roles_csv artifacts/rbac01-db-audit/roles.csv
\endif
\if :{?users_by_role_csv}
\else
\set users_by_role_csv artifacts/rbac01-db-audit/users_by_role.csv
\endif
\if :{?tenant_plans_csv}
\else
\set tenant_plans_csv artifacts/rbac01-db-audit/tenant_plans.csv
\endif
\if :{?tenant_modules_csv}
\else
\set tenant_modules_csv artifacts/rbac01-db-audit/tenant_modules.csv
\endif
\if :{?entitlements_csv}
\else
\set entitlements_csv artifacts/rbac01-db-audit/entitlements.csv
\endif
\if :{?role_permissions_csv}
\else
\set role_permissions_csv artifacts/rbac01-db-audit/role_permissions.csv
\endif
\if :{?dealer_assignments_csv}
\else
\set dealer_assignments_csv artifacts/rbac01-db-audit/dealer_assignments.csv
\endif

\pset pager off
\pset footer off
\pset null '[NULL]'
\timing on

\o :result_file
\echo RBAC-01 READ-ONLY DATABASE AUDIT
\echo Generated by RBAC01_DB_READONLY_AUDIT.sql
\echo

BEGIN;
SET TRANSACTION READ ONLY;
SET LOCAL statement_timeout = '120s';
SET LOCAL lock_timeout = '3s';

\echo == Connection Metadata ==
SELECT
  current_database() AS database_name,
  current_user AS database_user,
  version() AS postgres_version,
  now() AS audited_at;

\echo
\echo == RBAC / Commercial Schema Objects Found ==
SELECT
  table_schema,
  table_name,
  table_type
FROM information_schema.tables
WHERE table_schema = 'public'
  AND (
    table_name IN (
      'users',
      'roles',
      'user_roles',
      'app_roles',
      'permissions',
      'role_permissions',
      'tenants',
      'tenant_contracts',
      'tenant_subscriptions',
      'tenant_subscription_addons',
      'tenant_feature_overrides',
      'tenant_entitlements',
      'tenant_usage_limits',
      'usage_measurements',
      'trials',
      'commercial_plans',
      'commercial_plan_versions',
      'commercial_modules',
      'commercial_features',
      'commercial_technical_capabilities',
      'plan_version_modules',
      'module_features',
      'feature_capabilities',
      'saas_modules',
      'tenant_modules',
      'tenant_module_settings',
      'dealer_tenants',
      'dealer_tenant_access',
      'dealer_requests'
    )
    OR table_name LIKE 'v_tenant_%'
    OR table_name LIKE 'v_commercial_%'
    OR table_name LIKE 'v_dealer_%'
  )
ORDER BY table_type, table_name;

\echo
\echo == Relevant Columns Without Secret Values ==
SELECT
  table_name,
  column_name,
  data_type,
  is_nullable,
  column_default IS NOT NULL AS has_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN (
    'users',
    'roles',
    'user_roles',
    'app_roles',
    'permissions',
    'role_permissions',
    'tenants',
    'tenant_contracts',
    'tenant_subscriptions',
    'tenant_feature_overrides',
    'tenant_entitlements',
    'commercial_plans',
    'commercial_plan_versions',
    'commercial_modules',
    'commercial_technical_capabilities',
    'saas_modules',
    'tenant_modules',
    'tenant_module_settings',
    'dealer_tenants',
    'dealer_tenant_access'
  )
  AND column_name !~* '(password|hash|token|secret|credential|mfa|otp|api[_]?key|refresh)'
ORDER BY table_name, ordinal_position;

\echo
\echo == Role Values Found In users.role ==
\if :{?noop}
\endif
SELECT CASE WHEN to_regclass('public.users') IS NOT NULL THEN 'true' ELSE 'false' END AS has_users \gset
\if :has_users
SELECT
  lower(trim(role)) AS role_value,
  COUNT(*)::int AS users_count,
  COUNT(DISTINCT tenant_id)::int AS tenant_count
FROM public.users
WHERE role IS NOT NULL AND trim(role) <> ''
GROUP BY lower(trim(role))
ORDER BY users_count DESC, role_value;
\else
\echo public.users not found; users.role audit skipped.
\endif

\echo
\echo == Roles Registered In app_roles ==
SELECT CASE WHEN to_regclass('public.app_roles') IS NOT NULL THEN 'true' ELSE 'false' END AS has_app_roles \gset
\if :has_app_roles
SELECT
  role_key,
  display_name,
  role_level,
  is_system,
  is_active
FROM public.app_roles
ORDER BY role_level DESC NULLS LAST, role_key;
\else
\echo public.app_roles not found; app role registry audit skipped.
\endif

\echo
\echo == Legacy Role Candidate Presence ==
\if :has_users
WITH legacy_roles(role_value) AS (
  VALUES
    ('superadmin'),
    ('super_admin'),
    ('platform_admin'),
    ('admin_global'),
    ('global_admin'),
    ('owner'),
    ('admin'),
    ('tenant_admin'),
    ('admin_cumplimiento'),
    ('compliance_admin'),
    ('auditor'),
    ('operativo'),
    ('responsable_area'),
    ('area_owner'),
    ('viewer'),
    ('cliente'),
    ('client'),
    ('read_only'),
    ('readonly'),
    ('solo_lectura'),
    ('ejecutivo'),
    ('dealer')
)
SELECT
  lr.role_value,
  COUNT(u.id)::int AS users_count,
  COUNT(DISTINCT u.tenant_id)::int AS tenant_count
FROM legacy_roles lr
LEFT JOIN public.users u
  ON lower(trim(u.role)) = lr.role_value
GROUP BY lr.role_value
ORDER BY lr.role_value;
\else
\echo users table missing; legacy role presence by users skipped.
\endif

\echo
\echo == Permission Catalog Summary ==
SELECT CASE WHEN to_regclass('public.permissions') IS NOT NULL THEN 'true' ELSE 'false' END AS has_permissions \gset
\if :has_permissions
SELECT
  permission_group,
  COUNT(*)::int AS permission_count,
  COUNT(*) FILTER (WHERE is_active IS DISTINCT FROM FALSE)::int AS active_permission_count
FROM public.permissions
GROUP BY permission_group
ORDER BY permission_group;
\else
\echo public.permissions not found; permission catalog audit skipped.
\endif

\echo
\echo == Role Permission Summary ==
SELECT CASE WHEN to_regclass('public.role_permissions') IS NOT NULL THEN 'true' ELSE 'false' END AS has_role_permissions \gset
\if :has_role_permissions
SELECT
  role_key,
  COUNT(*) FILTER (WHERE is_allowed = true)::int AS allowed_permissions,
  COUNT(*) FILTER (WHERE is_allowed = false)::int AS denied_permissions,
  COUNT(*)::int AS total_mappings
FROM public.role_permissions
GROUP BY role_key
ORDER BY role_key;
\else
\echo public.role_permissions not found; role permission audit skipped.
\endif

\echo
\echo == Tenant Plans / Subscriptions Summary ==
SELECT CASE WHEN to_regclass('public.v_commercial_tenant_subscription') IS NOT NULL THEN 'true' ELSE 'false' END AS has_v_commercial_subscription \gset
SELECT CASE WHEN to_regclass('public.tenant_contracts') IS NOT NULL THEN 'true' ELSE 'false' END AS has_tenant_contracts \gset
\if :has_v_commercial_subscription
SELECT
  plan_key,
  status,
  COUNT(*)::int AS tenant_count
FROM public.v_commercial_tenant_subscription
GROUP BY plan_key, status
ORDER BY plan_key, status;
\elif :has_tenant_contracts
SELECT
  COALESCE(NULLIF(plan_key, ''), '[blank]') AS plan_key,
  COALESCE(contract_status, '[NULL]') AS status,
  COUNT(*)::int AS tenant_count
FROM public.tenant_contracts
GROUP BY COALESCE(NULLIF(plan_key, ''), '[blank]'), COALESCE(contract_status, '[NULL]')
ORDER BY plan_key, status;
\else
\echo commercial subscription and tenant_contracts objects not found; tenant plan audit skipped.
\endif

\echo
\echo == Module / Capability Summary ==
SELECT CASE WHEN to_regclass('public.v_tenant_modules') IS NOT NULL THEN 'true' ELSE 'false' END AS has_v_tenant_modules \gset
SELECT CASE WHEN to_regclass('public.v_commercial_tenant_modules') IS NOT NULL THEN 'true' ELSE 'false' END AS has_v_commercial_modules \gset
SELECT CASE WHEN to_regclass('public.v_commercial_tenant_capabilities') IS NOT NULL THEN 'true' ELSE 'false' END AS has_v_commercial_capabilities \gset
\if :has_v_tenant_modules
SELECT
  module_key,
  is_enabled,
  COUNT(*)::int AS tenant_count
FROM public.v_tenant_modules
GROUP BY module_key, is_enabled
ORDER BY module_key, is_enabled;
\elif :has_v_commercial_modules
SELECT
  module_key,
  enabled AS is_enabled,
  COUNT(*)::int AS tenant_count
FROM public.v_commercial_tenant_modules
GROUP BY module_key, enabled
ORDER BY module_key, enabled;
\else
\echo tenant module views not found; module mapping audit skipped.
\endif

\if :has_v_commercial_capabilities
SELECT
  capability_key,
  enabled,
  read_only,
  source,
  COUNT(*)::int AS tenant_count
FROM public.v_commercial_tenant_capabilities
GROUP BY capability_key, enabled, read_only, source
ORDER BY capability_key, source;
\else
\echo v_commercial_tenant_capabilities not found; capability mapping summary skipped.
\endif

\echo
\echo == Dealer / MSP Summary ==
SELECT CASE WHEN to_regclass('public.dealer_tenants') IS NOT NULL THEN 'true' ELSE 'false' END AS has_dealer_tenants \gset
SELECT CASE WHEN to_regclass('public.dealer_tenant_access') IS NOT NULL THEN 'true' ELSE 'false' END AS has_dealer_access \gset
\if :has_dealer_tenants
SELECT
  status,
  COUNT(*)::int AS assignment_count,
  COUNT(DISTINCT dealer_user_id)::int AS dealer_count,
  COUNT(DISTINCT tenant_id)::int AS tenant_count
FROM public.dealer_tenants
GROUP BY status
ORDER BY status;
\elif :has_dealer_access
SELECT
  status,
  COUNT(*)::int AS assignment_count,
  COUNT(DISTINCT dealer_user_id)::int AS dealer_count,
  COUNT(DISTINCT tenant_id)::int AS tenant_count
FROM public.dealer_tenant_access
GROUP BY status
ORDER BY status;
\else
\echo dealer assignment objects not found; dealer audit skipped.
\endif

\echo
\echo == Role / Permission Constraints And Enums ==
SELECT
  n.nspname AS schema_name,
  c.relname AS table_name,
  con.conname AS constraint_name,
  con.contype AS constraint_type,
  pg_get_constraintdef(con.oid) AS definition
FROM pg_constraint con
JOIN pg_class c ON c.oid = con.conrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND (
    c.relname IN (
      'users',
      'roles',
      'user_roles',
      'app_roles',
      'permissions',
      'role_permissions',
      'tenants',
      'tenant_subscriptions',
      'tenant_entitlements',
      'tenant_feature_overrides',
      'commercial_plans',
      'commercial_plan_versions',
      'commercial_modules',
      'commercial_technical_capabilities',
      'saas_modules',
      'tenant_modules',
      'tenant_module_settings',
      'dealer_tenants',
      'dealer_tenant_access'
    )
    OR con.conname ILIKE '%role%'
    OR con.conname ILIKE '%permission%'
    OR con.conname ILIKE '%plan%'
    OR con.conname ILIKE '%module%'
    OR con.conname ILIKE '%entitlement%'
  )
ORDER BY c.relname, con.conname;

SELECT
  ns.nspname AS schema_name,
  typ.typname AS enum_name,
  enum.enumlabel AS enum_value,
  enum.enumsortorder
FROM pg_type typ
JOIN pg_namespace ns ON ns.oid = typ.typnamespace
JOIN pg_enum enum ON enum.enumtypid = typ.oid
WHERE ns.nspname = 'public'
  AND (
    typ.typname ILIKE '%role%'
    OR typ.typname ILIKE '%permission%'
    OR typ.typname ILIKE '%plan%'
    OR typ.typname ILIKE '%module%'
    OR typ.typname ILIKE '%entitlement%'
  )
ORDER BY typ.typname, enum.enumsortorder;

\echo
\echo == Sensitive Columns Confirmed Not Extracted ==
SELECT
  table_name,
  column_name,
  data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND column_name ~* '(password|hash|token|secret|credential|mfa|otp|api[_]?key|refresh)'
ORDER BY table_name, column_name;

\echo
\echo == CSV Exports ==
\if :has_app_roles
\echo Writing :roles_csv from public.app_roles
\o :roles_csv
COPY (
  SELECT
    role_key,
    display_name,
    description,
    role_level,
    is_system,
    is_active
  FROM public.app_roles
  ORDER BY role_level DESC NULLS LAST, role_key
) TO STDOUT WITH CSV HEADER;
\o :result_file
\elif :has_users
\echo Writing :roles_csv from distinct public.users.role values
\o :roles_csv
COPY (
  SELECT
    lower(trim(role)) AS role_value,
    COUNT(*)::int AS users_count,
    COUNT(DISTINCT tenant_id)::int AS tenant_count
  FROM public.users
  WHERE role IS NOT NULL AND trim(role) <> ''
  GROUP BY lower(trim(role))
  ORDER BY role_value
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
\echo roles.csv skipped; no role source table found.
\endif

\if :has_users
\echo Writing :users_by_role_csv
\o :users_by_role_csv
COPY (
  SELECT
    tenant_id,
    lower(trim(role)) AS role_value,
    COUNT(*)::int AS users_count
  FROM public.users
  WHERE role IS NOT NULL AND trim(role) <> ''
  GROUP BY tenant_id, lower(trim(role))
  ORDER BY tenant_id, role_value
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
\echo users_by_role.csv skipped; public.users not found.
\endif

\if :has_role_permissions
\echo Writing :role_permissions_csv
\o :role_permissions_csv
COPY (
  SELECT
    rp.role_key,
    rp.permission_key,
    rp.is_allowed,
    p.permission_group,
    p.is_active AS permission_is_active
  FROM public.role_permissions rp
  LEFT JOIN public.permissions p ON p.permission_key = rp.permission_key
  ORDER BY rp.role_key, rp.permission_key
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
\echo role_permissions.csv skipped; public.role_permissions not found.
\endif

\if :has_v_commercial_subscription
\echo Writing :tenant_plans_csv from v_commercial_tenant_subscription
\o :tenant_plans_csv
COPY (
  SELECT
    tenant_id,
    plan_key,
    plan_display_name,
    status,
    started_at,
    ended_at,
    version_number
  FROM public.v_commercial_tenant_subscription
  ORDER BY tenant_id, started_at DESC
) TO STDOUT WITH CSV HEADER;
\o :result_file
\elif :has_tenant_contracts
\echo Writing :tenant_plans_csv from tenant_contracts
\o :tenant_plans_csv
COPY (
  SELECT
    tenant_id,
    plan_key,
    contract_status AS status,
    started_at,
    ends_at
  FROM public.tenant_contracts
  ORDER BY tenant_id, created_at DESC NULLS LAST
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
\echo tenant_plans.csv skipped; no plan source found.
\endif

\if :has_v_tenant_modules
\echo Writing :tenant_modules_csv from v_tenant_modules
\o :tenant_modules_csv
COPY (
  SELECT
    tenant_id,
    module_key,
    module_name,
    is_enabled,
    enabled_at,
    disabled_at
  FROM public.v_tenant_modules
  ORDER BY tenant_id, sort_order, module_key
) TO STDOUT WITH CSV HEADER;
\o :result_file
\elif :has_v_commercial_modules
\echo Writing :tenant_modules_csv from v_commercial_tenant_modules
\o :tenant_modules_csv
COPY (
  SELECT
    tenant_id,
    plan_key,
    module_key,
    display_name AS module_name,
    enabled AS is_enabled,
    source
  FROM public.v_commercial_tenant_modules
  ORDER BY tenant_id, sort_order, module_key
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
\echo tenant_modules.csv skipped; no tenant module source found.
\endif

\if :has_v_commercial_capabilities
\echo Writing :entitlements_csv from v_commercial_tenant_capabilities
\o :entitlements_csv
COPY (
  SELECT
    tenant_id,
    capability_key,
    enabled,
    read_only,
    source,
    module_key,
    required_permission,
    effective_from,
    effective_until
  FROM public.v_commercial_tenant_capabilities
  ORDER BY tenant_id, capability_key, source
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
SELECT CASE WHEN to_regclass('public.tenant_entitlements') IS NOT NULL THEN 'true' ELSE 'false' END AS has_tenant_entitlements \gset
\if :has_tenant_entitlements
\echo Writing :entitlements_csv from tenant_entitlements
\o :entitlements_csv
COPY (
  SELECT
    tenant_id,
    capability_key,
    source,
    enabled,
    read_only,
    effective_from,
    effective_until,
    reason
  FROM public.tenant_entitlements
  ORDER BY tenant_id, capability_key, source
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
\echo entitlements.csv skipped; no entitlement source found.
\endif
\endif

\if :has_dealer_tenants
\echo Writing :dealer_assignments_csv from dealer_tenants
\o :dealer_assignments_csv
COPY (
  SELECT
    dealer_user_id,
    tenant_id,
    status,
    assigned_at,
    revoked_at
  FROM public.dealer_tenants
  ORDER BY dealer_user_id, tenant_id
) TO STDOUT WITH CSV HEADER;
\o :result_file
\elif :has_dealer_access
\echo Writing :dealer_assignments_csv from dealer_tenant_access
\o :dealer_assignments_csv
COPY (
  SELECT
    dealer_user_id,
    tenant_id,
    status
  FROM public.dealer_tenant_access
  ORDER BY dealer_user_id, tenant_id
) TO STDOUT WITH CSV HEADER;
\o :result_file
\else
\echo dealer_assignments.csv skipped; no dealer assignment source found.
\endif

\echo
\echo RBAC-01 read-only SQL finished. Rolling back read-only transaction.
ROLLBACK;
\echo
\echo No database rows were modified by this audit.
\o
