'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { ApiClientError, apiRequestJson, apiRequestJsonSingleFlight } from '@/utils/apiClient';
import { getUserRoleFromToken } from '@/utils/auth';

type UnknownRecord = Record<string, unknown>;
type Definition = { id:string;code:string;name:string;definition:string;domain:string;objective:string;unit:string;direction:string;frequency:string;population:string;version:number;status:string };
type Snapshot = { snapshot_id:string;period?:{key?:string;start?:string;end?:string};effective_at?:string;value:number|null;unit?:string;state:string;target?:number|null;coverage?:number|null;trust?:{score?:number|null;status?:string};freshness?:{status?:string};sufficiency?:{status?:string};interpretation?:{classification?:{label?:string;positive?:boolean};trend?:string;cause?:string|null;impact?:string|null;recommendation?:string|null;proposed_action?:string|null};updated_at?:string;checksum?:string };
type CatalogItem = { definition:Definition;latest_snapshot:Snapshot|null };
type Comparison = { id?:string;comparison_type?:string;status?:string;absolute_change?:number|null;percentage_change?:number|null;methodology_compatible?:boolean;compatibility_reason?:string|null;created_at?:string };

const ADMIN_ROLES=new Set(['admin','tenant_admin','superadmin','super_admin','platform_admin','admin_global','global_admin','owner','data_steward']);
const TECHNICAL_ROLES=new Set([...ADMIN_ROLES,'auditor']);
function record(value:unknown):UnknownRecord{return typeof value==='object'&&value!==null&&!Array.isArray(value)?value as UnknownRecord:{}}
function data<T>(payload:unknown):T{const root=record(payload);return (root.data??payload) as T}
function formatValue(snapshot:Snapshot|null){if(!snapshot||snapshot.state!=='calculated'||snapshot.value===null)return 'Sin medición';return `${new Intl.NumberFormat('es-CL',{maximumFractionDigits:2}).format(snapshot.value)}${snapshot.unit==='%'?' %':snapshot.unit?` ${snapshot.unit}`:''}`}
function statusClass(snapshot:Snapshot|null){if(!snapshot||snapshot.state!=='calculated')return 'border-slate-300 bg-slate-100 text-slate-700';if(snapshot.interpretation?.classification?.positive)return 'border-emerald-200 bg-emerald-50 text-emerald-900';return 'border-amber-200 bg-amber-50 text-amber-950'}
function pct(value:number|null|undefined){return value===null||value===undefined?'Desconocida':`${Math.round(value*(value<=1?100:1)*100)/100}%`}

export default function FunctionalIndicatorCatalog({ metricCode }: { metricCode?:string }){
  const role=getUserRoleFromToken();const canOperate=ADMIN_ROLES.has(role);const canTechnical=TECHNICAL_ROLES.has(role);
  const [items,setItems]=useState<CatalogItem[]>([]);const [selected,setSelected]=useState<CatalogItem|null>(null);const [technical,setTechnical]=useState<UnknownRecord|null>(null);const [history,setHistory]=useState<Snapshot[]>([]);const [comparisons,setComparisons]=useState<Comparison[]>([]);const [draftSnapshotId,setDraftSnapshotId]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [search,setSearch]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{if(metricCode){const encoded=encodeURIComponent(metricCode);const [itemPayload,historyPayload,comparisonPayload]=await Promise.all([apiRequestJsonSingleFlight(`/api/metrics/official/${encoded}`,{fallbackMessage:'No fue posible cargar el indicador oficial.'}),apiRequestJsonSingleFlight(`/api/metrics/official/${encoded}/history?limit=24`,{fallbackMessage:'No fue posible cargar el historial oficial.'}),apiRequestJsonSingleFlight(`/api/metrics/official/${encoded}/comparisons?limit=24`,{fallbackMessage:'No fue posible cargar las comparaciones.'})]);const item=data<CatalogItem>(itemPayload);setItems([item]);setSelected(item);const historic=data<Snapshot[]>(historyPayload);const compared=data<Comparison[]>(comparisonPayload);setHistory(Array.isArray(historic)?historic:[]);setComparisons(Array.isArray(compared)?compared:[]);}else{const rows=data<CatalogItem[]>(await apiRequestJsonSingleFlight('/api/metrics/official/catalog',{fallbackMessage:'No fue posible cargar el catálogo funcional.'}));setItems(Array.isArray(rows)?rows:[]);}}catch(err){setError(err instanceof ApiClientError||err instanceof Error?err.message:'No fue posible cargar indicadores.');}finally{setLoading(false)}},[metricCode]);
  useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>items.filter((item)=>!search.trim()||`${item.definition.name} ${item.definition.definition} ${item.definition.domain}`.toLowerCase().includes(search.trim().toLowerCase())),[items,search]);
  async function operate(kind:'calculate'|'snapshot'|'publish'|'proposal'){
    if(!selected)return;setBusy(kind);setError('');try{
      if(kind==='calculate'){const now=new Date();const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));await apiRequestJson(`/api/metrics/official/${encodeURIComponent(selected.definition.code)}/calculate`,{method:'POST',body:JSON.stringify({period:{key:now.toISOString().slice(0,7),start:start.toISOString(),end:now.toISOString(),timezone:'America/Santiago'}}),fallbackMessage:'No fue posible calcular el indicador.'});}
      if(kind==='snapshot'){const created=data<{snapshot?:{snapshot_id?:string}}>(await apiRequestJson(`/api/metrics/official/${encodeURIComponent(selected.definition.code)}/snapshots`,{method:'POST',body:'{}',fallbackMessage:'No fue posible crear el snapshot.'}));setDraftSnapshotId(String(created.snapshot?.snapshot_id||''));}
      if(kind==='publish'&&draftSnapshotId){await apiRequestJson(`/api/metrics/official/snapshots/${encodeURIComponent(draftSnapshotId)}/publish`,{method:'POST',body:'{}',fallbackMessage:'No fue posible publicar el snapshot.'});setDraftSnapshotId('');}
      if(kind==='proposal'&&selected.latest_snapshot)await apiRequestJson(`/api/metrics/official/snapshots/${selected.latest_snapshot.snapshot_id}/proposals`,{method:'POST',body:JSON.stringify({title:`Revisar ${selected.definition.name}`,rationale:selected.latest_snapshot.interpretation?.recommendation||'El resultado oficial requiere revisión.',priority:'attention'}),fallbackMessage:'No fue posible registrar la propuesta.'});
      await load();
    }catch(err){setError(err instanceof ApiClientError||err instanceof Error?err.message:'No fue posible completar la operación.');}finally{setBusy('')}
  }
  async function loadTechnical(){if(!selected||!canTechnical)return;setBusy('technical');setError('');try{const payload=data<UnknownRecord>(await apiRequestJson(`/api/metrics/official/${encodeURIComponent(selected.definition.code)}/technical`,{fallbackMessage:'No fue posible cargar el detalle técnico.'}));setTechnical(record(payload.technical));}catch(err){setError(err instanceof ApiClientError||err instanceof Error?err.message:'No fue posible cargar el detalle técnico.');}finally{setBusy('')}}
  if(loading)return <div role="status" className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-600">Cargando indicadores oficiales…</div>;
  return <div className="space-y-5">
    {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-900">{error}</div>}
    {!metricCode&&<label className="block text-sm font-semibold text-slate-800">Buscar concepto<input value={search} onChange={(event)=>setSearch(event.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 px-3 font-normal" placeholder="Cumplimiento, riesgo, evidencia…" /></label>}
    {!metricCode&&<div className="grid gap-4 lg:grid-cols-2">{visible.map((item)=><article key={item.definition.code} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-blue-700">{item.definition.domain}</p><h2 className="mt-1 text-lg font-bold text-slate-950">{item.definition.name}</h2></div><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${statusClass(item.latest_snapshot)}`}>{item.latest_snapshot?.interpretation?.classification?.label||item.latest_snapshot?.state||'Sin medición'}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{item.definition.definition}</p><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><span className="block text-xs text-slate-500">Resultado</span><strong>{formatValue(item.latest_snapshot)}</strong></div><div><span className="block text-xs text-slate-500">Cobertura</span><strong>{pct(item.latest_snapshot?.coverage)}</strong></div><div><span className="block text-xs text-slate-500">Confianza</span><strong>{item.latest_snapshot?.trust?.score??'Desconocida'}</strong></div></div><Link href={`/metricas/${encodeURIComponent(item.definition.code)}`} className="mt-4 inline-flex min-h-10 items-center rounded-lg border border-blue-200 px-3 text-sm font-semibold text-blue-800 hover:bg-blue-50">Abrir indicador</Link></article>)}</div>}
    {selected&&<article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">{selected.definition.domain}</p><h1 className="mt-1 text-2xl font-bold text-slate-950">{selected.definition.name}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{selected.definition.definition}</p></div><span className={`self-start rounded-full border px-3 py-1 text-xs font-semibold ${statusClass(selected.latest_snapshot)}`}>{selected.latest_snapshot?.interpretation?.classification?.label||selected.latest_snapshot?.state||'Sin medición'}</span></div>
      <dl className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Resultado oficial" value={formatValue(selected.latest_snapshot)}/><Field label="Período" value={selected.latest_snapshot?.period?.key||'No disponible'}/><Field label="Cobertura" value={pct(selected.latest_snapshot?.coverage)}/><Field label="Data Trust" value={`${selected.latest_snapshot?.trust?.score??'Desconocido'} · ${selected.latest_snapshot?.trust?.status||'unknown'}`}/><Field label="Freshness" value={selected.latest_snapshot?.freshness?.status||'unknown'}/><Field label="Suficiencia" value={selected.latest_snapshot?.sufficiency?.status||'source_unavailable'}/><Field label="Tendencia" value={selected.latest_snapshot?.interpretation?.trend||'unknown'}/><Field label="Actualizado" value={selected.latest_snapshot?.updated_at?new Date(selected.latest_snapshot.updated_at).toLocaleString('es-CL'):'Sin evidencia'}/></dl>
      <section className="mt-6 grid gap-4 lg:grid-cols-3"><TextBlock title="Causa" value={selected.latest_snapshot?.interpretation?.cause}/><TextBlock title="Impacto" value={selected.latest_snapshot?.interpretation?.impact}/><TextBlock title="Recomendación" value={selected.latest_snapshot?.interpretation?.recommendation}/></section>
      {canOperate&&<div className="mt-6 flex flex-wrap gap-2"><Action disabled={Boolean(busy)} onClick={()=>operate('calculate')}>{busy==='calculate'?'Calculando…':'Calcular desde fuentes'}</Action><Action disabled={Boolean(busy)} onClick={()=>operate('snapshot')}>{busy==='snapshot'?'Creando…':'Crear snapshot draft'}</Action>{draftSnapshotId&&<Action disabled={Boolean(busy)} onClick={()=>operate('publish')}>{busy==='publish'?'Publicando…':'Publicar snapshot revisado'}</Action>}{selected.latest_snapshot&&<Action disabled={Boolean(busy)} onClick={()=>operate('proposal')}>{busy==='proposal'?'Registrando…':'Proponer acción'}</Action>}</div>}
      {metricCode&&<section className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-slate-200 p-4"><h2 className="font-bold text-slate-900">Historial oficial</h2>{history.length?<ol className="mt-3 space-y-2">{history.map((snapshot)=><li key={snapshot.snapshot_id} className="flex justify-between gap-3 text-sm"><span>{snapshot.period?.key||'Período sin etiqueta'}</span><strong>{formatValue(snapshot)}</strong></li>)}</ol>:<p className="mt-2 text-sm text-slate-600">Aún no hay snapshots publicados.</p>}</div><div className="rounded-lg border border-slate-200 p-4"><h2 className="font-bold text-slate-900">Comparabilidad metodológica</h2>{comparisons.length?<ol className="mt-3 space-y-2">{comparisons.map((comparison,index)=><li key={comparison.id||String(index)} className="text-sm"><strong>{comparison.methodology_compatible===false?'No comparable':comparison.status||'Comparable'}</strong><span className="block text-slate-600">{comparison.compatibility_reason||`Cambio absoluto: ${comparison.absolute_change??'desconocido'}`}</span></li>)}</ol>:<p className="mt-2 text-sm text-slate-600">Sin comparaciones publicadas.</p>}</div></section>}
      {canTechnical&&<details className="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-4" onToggle={(event)=>{if(event.currentTarget.open&&!technical&&!busy)void loadTechnical()}}><summary className="cursor-pointer font-semibold text-slate-800">Detalle técnico autorizado</summary>{busy==='technical'?<p className="mt-3 text-sm text-slate-600">Cargando trazabilidad…</p>:technical?<TechnicalDetail value={technical}/>:<p className="mt-3 text-sm text-slate-600">Metodología, binding, versiones y lineage.</p>}</details>}
    </article>}
  </div>
}

function Field({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="font-semibold text-slate-950">{value}</dd></div>}
function TextBlock({title,value}:{title:string;value?:string|null}){return <div className="rounded-lg border border-slate-200 p-4"><h3 className="text-xs font-bold uppercase tracking-wide text-slate-500">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-800">{value||'No existe evidencia suficiente para afirmar este punto.'}</p></div>}
function Action({children,disabled,onClick}:{children:ReactNode;disabled:boolean;onClick:()=>void}){return <button type="button" disabled={disabled} onClick={onClick} className="min-h-11 rounded-lg bg-blue-700 px-4 text-sm font-semibold text-white disabled:opacity-50">{children}</button>}
function TechnicalDetail({value}:{value:UnknownRecord}){const formula=record(value.formula);const binding=record(value.binding);const policy=record(value.calculation_policy);const trust=record(value.trust_policy);const lineage=Array.isArray(value.lineage)?value.lineage:[];return <dl className="mt-4 grid gap-3 text-sm md:grid-cols-2"><Field label="Fórmula oficial" value={String(formula.code||'No disponible')}/><Field label="Versión de definición" value={String(value.definition_version||'No disponible')}/><Field label="Binding" value={`v${String(binding.version||'?')} · ${String(binding.checksum||'sin checksum')}`}/><Field label="Política de cálculo" value={`v${String(policy.version||'?')} · timeout ${String(policy.timeout_ms||'?')} ms`}/><Field label="Política Data Trust" value={`v${String(trust.version||'?')} · ${String(trust.checksum||'sin checksum')}`}/><Field label="Lineage" value={`${lineage.length} relaciones registradas`}/></dl>}
