'use strict';

const VERSION = 'universal-excel-v1';

const text = (key, label, options = {}) => ({ key, label, type: 'text', ...options });
const number = (key, label, options = {}) => ({ key, label, type: 'number', ...options });
const date = (key, label, options = {}) => ({ key, label, type: 'date', ...options });
const relation = (key, label, catalog, options = {}) => ({
  key,
  label,
  type: 'relation',
  catalog,
  ...options,
});
const choice = (key, label, values, options = {}) => ({
  key,
  label,
  type: 'enum',
  values,
  ...options,
});

const common = {
  version: VERSION,
  requiredPermissions: ['operations.import'],
  requiredCapability: 'grc_phase3_operations',
  duplicatePolicies: ['create_only', 'update_existing', 'create_or_update', 'reject_duplicates'],
  maximumRows: 5000,
  maximumFileSize: 5 * 1024 * 1024,
};

const enabled = ({
  entityType,
  wave,
  displayName,
  description,
  adapter,
  dependencies = [],
  fields,
  naturalKey = ['code'],
  duplicatePolicy = 'create_only',
  duplicatePolicies = ['create_only', 'update_existing', 'create_or_update', 'reject_duplicates'],
  rollbackPolicy = 'batch_only',
}) => ({
  ...common,
  entityType,
  wave,
  displayName,
  description,
  adapter,
  dependencies,
  fields,
  naturalKey,
  duplicatePolicy,
  duplicatePolicies,
  createPolicy: 'allowed',
  updatePolicy: duplicatePolicy === 'create_only' ? 'blocked' : 'allowed',
  rollbackPolicy,
  availability: 'importable_now',
});

const blocked = ({
  entityType,
  wave,
  displayName,
  description,
  classification,
  reason,
  dependencies = [],
}) => ({
  ...common,
  entityType,
  wave,
  displayName,
  description,
  dependencies,
  fields: [],
  naturalKey: [],
  duplicatePolicy: 'reject_duplicates',
  createPolicy: 'blocked',
  updatePolicy: 'blocked',
  rollbackPolicy: 'not_applicable',
  availability: 'blocked',
  classification,
  blockedReason: reason,
});

const DEFINITIONS = [
  enabled({
    entityType: 'organizations',
    wave: 1,
    displayName: 'Unidades',
    description: 'Estructura organizacional y responsables.',
    adapter: 'phase3.createOrganization',
    fields: [
      text('code', 'Código', { required: true, maxLength: 80 }),
      text('name', 'Nombre', { required: true, maxLength: 240 }),
      text('description', 'Descripción'),
      choice('unit_type', 'Tipo', ['department', 'area', 'business_unit', 'location'], { required: true }),
      relation('owner_email', 'Responsable', 'users'),
      text('location_reference', 'Ubicación'),
      date('next_review_at', 'Próxima revisión'),
    ],
  }),
  blocked({
    entityType: 'users',
    wave: 1,
    displayName: 'Usuarios',
    description: 'Altas de usuarios y asignación inicial.',
    classification: 'security_sensitive',
    reason: 'El alta requiere invitación, verificación de identidad y política de credenciales. No se importan contraseñas.',
  }),
  enabled({
    entityType: 'processes',
    wave: 1,
    displayName: 'Procesos',
    description: 'Procesos vinculados a unidades y responsables.',
    adapter: 'phase3.createProcess',
    dependencies: ['organizations'],
    fields: [
      text('code', 'Código', { required: true, maxLength: 80 }),
      text('name', 'Nombre', { required: true, maxLength: 240 }),
      text('description', 'Descripción'),
      choice('process_type', 'Tipo', ['strategic', 'operational', 'support'], { required: true }),
      relation('unit_code', 'Unidad', 'organization'),
      relation('owner_email', 'Responsable', 'users'),
      choice('criticality', 'Criticidad', ['low', 'medium', 'high', 'critical']),
      number('criticality_score', 'Puntaje de criticidad', { required: true, minimum: 0, maximum: 100 }),
      text('objective', 'Objetivo'),
      text('scope', 'Alcance'),
      date('review_due_at', 'Próxima revisión'),
    ],
  }),
  enabled({
    entityType: 'services',
    wave: 1,
    displayName: 'Servicios',
    description: 'Servicios operacionales relacionados con procesos.',
    adapter: 'phase3.createService',
    dependencies: ['organizations', 'processes'],
    fields: [
      text('code', 'Código', { required: true }),
      text('name', 'Nombre', { required: true }),
      text('description', 'Descripción'),
      relation('unit_code', 'Unidad', 'organization'),
      relation('process_code', 'Proceso', 'process'),
      relation('owner_email', 'Responsable', 'users'),
      text('minimum_service_level', 'Nivel mínimo', { required: true }),
      choice('criticality', 'Criticidad', ['low', 'medium', 'high', 'critical'], { required: true }),
      number('rto_minutes', 'RTO minutos', { minimum: 0 }),
      number('rpo_minutes', 'RPO minutos', { minimum: 0 }),
      number('mtpd_minutes', 'MTPD minutos', { minimum: 0 }),
      date('next_review_at', 'Próxima revisión'),
    ],
  }),
  blocked({
    entityType: 'assets',
    wave: 1,
    displayName: 'Activos',
    description: 'Activos de información, tecnológicos y físicos.',
    classification: 'importable_after_code',
    reason: 'El modelo actual no garantiza un código natural único y estable por tenant para todos los activos.',
  }),
  enabled({
    entityType: 'suppliers',
    wave: 1,
    displayName: 'Proveedores',
    description: 'Terceros y criticidad inicial.',
    adapter: 'phase2.createSupplier',
    duplicatePolicies: ['create_only', 'reject_duplicates'],
    fields: [
      text('code', 'Código', { required: true }),
      text('legal_name', 'Razón social', { required: true }),
      text('trade_name', 'Nombre comercial'),
      text('tax_identifier', 'Identificador tributario'),
      text('country_code', 'País ISO-3', { maxLength: 3 }),
      choice('criticality', 'Criticidad', ['low', 'medium', 'high', 'critical']),
      number('inherent_risk_score', 'Riesgo inherente', { minimum: 0, maximum: 100 }),
      number('residual_risk_score', 'Riesgo residual', { minimum: 0, maximum: 100 }),
      relation('owner_email', 'Responsable', 'users'),
      choice('data_access_level', 'Acceso a datos', ['none', 'internal', 'confidential', 'restricted']),
      text('access_summary', 'Resumen de acceso'),
      date('next_assessment_at', 'Próxima evaluación'),
    ],
  }),
  enabled({
    entityType: 'bia',
    wave: 1,
    displayName: 'BIA',
    description: 'Evaluaciones de impacto al negocio.',
    adapter: 'phase3.createBia',
    dependencies: ['processes', 'services'],
    fields: [
      text('code', 'Código', { required: true }),
      relation('process_code', 'Proceso', 'process'),
      relation('service_code', 'Servicio', 'service'),
      relation('owner_email', 'Responsable', 'users'),
      date('assessment_date', 'Fecha de evaluación'),
      text('assumptions', 'Supuestos', { required: true }),
      number('estimated_financial_impact', 'Impacto financiero', { minimum: 0 }),
      number('mtpd_minutes', 'MTPD minutos', { required: true, minimum: 0 }),
      number('rto_minutes', 'RTO minutos', { required: true, minimum: 0 }),
      number('rpo_minutes', 'RPO minutos', { required: true, minimum: 0 }),
      text('minimum_service_level', 'Nivel mínimo'),
      number('required_people', 'Personas requeridas', { minimum: 0 }),
      text('alternative_resources', 'Recursos alternativos'),
      date('next_review_at', 'Próxima revisión', { required: true }),
    ],
  }),
  enabled({
    entityType: 'continuity_plans',
    wave: 1,
    displayName: 'Planes de continuidad',
    description: 'Planes relacionados con procesos, servicios y BIA.',
    adapter: 'phase3.createContinuityPlan',
    dependencies: ['bia'],
    fields: [
      text('code', 'Código', { required: true }),
      text('name', 'Nombre', { required: true }),
      text('scope', 'Alcance', { required: true }),
      relation('process_code', 'Proceso', 'process'),
      relation('service_code', 'Servicio', 'service'),
      relation('bia_code', 'BIA', 'bia'),
      relation('activation_authority_email', 'Autoridad de activación', 'users'),
      text('activation_criteria', 'Criterio de activación', { required: true }),
      text('procedures', 'Procedimientos', { required: true }),
      text('recovery_sequence', 'Secuencia de recuperación', { required: true }),
      text('communication_plan', 'Plan de comunicación'),
      text('return_to_operation_criteria', 'Criterio de retorno', { required: true }),
      date('valid_from', 'Vigente desde'),
      date('valid_until', 'Vigente hasta'),
      date('next_review_at', 'Próxima revisión', { required: true }),
    ],
  }),
  enabled({
    entityType: 'continuity_tests',
    wave: 1,
    displayName: 'Pruebas de continuidad',
    description: 'Programación de pruebas vinculadas a un plan.',
    adapter: 'phase3.createContinuityTest',
    duplicatePolicies: ['create_only', 'reject_duplicates'],
    dependencies: ['continuity_plans'],
    naturalKey: ['plan_code', 'scheduled_at', 'test_type'],
    fields: [
      relation('plan_code', 'Plan', 'continuity_plan', { required: true }),
      choice('test_type', 'Tipo', ['tabletop', 'simulation', 'technical', 'full'], { required: true }),
      text('objective', 'Objetivo', { required: true }),
      text('scenario', 'Escenario', { required: true }),
      text('scope', 'Alcance', { required: true }),
      date('scheduled_at', 'Fecha programada', { required: true }),
      text('expected_result', 'Resultado esperado', { required: true }),
      number('target_rto_minutes', 'RTO objetivo', { minimum: 0 }),
      number('target_rpo_minutes', 'RPO objetivo', { minimum: 0 }),
      date('next_test_at', 'Próxima prueba'),
    ],
  }),
  enabled({
    entityType: 'metrics',
    wave: 1,
    displayName: 'Indicadores',
    description: 'Definiciones KPI, KRI y KCI.',
    adapter: 'phase3.createMetric',
    fields: [
      text('code', 'Código', { required: true }),
      text('name', 'Nombre', { required: true }),
      text('description', 'Descripción'),
      choice('metric_type', 'Tipo', ['kpi', 'kri', 'kci'], { required: true }),
      choice('entity_type', 'Dominio relacionado', ['organization', 'process', 'service', 'supplier', 'risk', 'control'], { required: true }),
      text('entity_code', 'Código relacionado', { required: true }),
      relation('owner_email', 'Responsable', 'users'),
      text('formula_definition', 'Definición de cálculo', { required: true }),
      text('source_description', 'Fuente', { required: true }),
      text('frequency', 'Frecuencia', { required: true }),
      text('unit', 'Unidad de medida', { required: true }),
      choice('expected_direction', 'Dirección esperada', ['higher_is_better', 'lower_is_better', 'target'], { required: true }),
      number('target_value', 'Meta', { required: true }),
      number('warning_threshold', 'Umbral advertencia', { required: true }),
      number('critical_threshold', 'Umbral crítico', { required: true }),
      text('measurement_window', 'Ventana de medición', { required: true }),
    ],
  }),
  enabled({
    entityType: 'metric_measurements',
    wave: 1,
    displayName: 'Mediciones',
    description: 'Valores observados para indicadores existentes.',
    adapter: 'phase3.recordMeasurement',
    duplicatePolicies: ['create_only', 'reject_duplicates'],
    dependencies: ['metrics'],
    naturalKey: ['metric_code', 'period_start', 'period_end'],
    fields: [
      relation('metric_code', 'Indicador', 'metric', { required: true }),
      date('period_start', 'Inicio del período', { required: true }),
      date('period_end', 'Fin del período', { required: true }),
      number('numeric_value', 'Valor', { required: true }),
      text('source_description', 'Fuente', { required: true }),
      date('measured_at', 'Fecha de medición'),
      choice('quality', 'Calidad', ['valid', 'estimated', 'rejected']),
      text('comment', 'Comentario'),
    ],
  }),
  enabled({
    entityType: 'quantitative_risks',
    wave: 1,
    displayName: 'Riesgo cuantitativo',
    description: 'Escenarios cuantitativos vinculados a riesgos.',
    adapter: 'phase3.createQuantitativeRisk',
    dependencies: ['risks'],
    fields: [
      text('code', 'Código', { required: true }),
      relation('risk_code', 'Riesgo', 'risk', { required: true }),
      relation('unit_code', 'Unidad', 'organization'),
      relation('process_code', 'Proceso', 'process'),
      relation('service_code', 'Servicio', 'service'),
      text('scenario', 'Escenario', { required: true }),
      number('minimum_impact', 'Impacto mínimo', { required: true, minimum: 0 }),
      number('most_likely_impact', 'Impacto más probable', { required: true, minimum: 0 }),
      number('maximum_impact', 'Impacto máximo', { required: true, minimum: 0 }),
      number('estimated_frequency', 'Frecuencia estimada', { required: true, minimum: 0 }),
      number('residual_annualized_loss', 'Pérdida residual', { minimum: 0 }),
      number('treatment_annualized_loss', 'Pérdida con tratamiento', { minimum: 0 }),
      number('control_cost', 'Costo del control', { minimum: 0 }),
      number('expected_reduction', 'Reducción esperada', { minimum: 0 }),
      text('assumptions', 'Supuestos', { required: true }),
      text('source_description', 'Fuente', { required: true }),
    ],
  }),
];

const blockedDomains = [
  ['risks', 2, 'Riesgos', 'importable_after_code', 'El flujo vigente calcula y versiona la matriz; requiere un adaptador transaccional específico.'],
  ['controls', 2, 'Controles', 'importable_after_code', 'Existen variantes de catálogo y control tenant; falta una clave natural única transversal.'],
  ['treatments', 2, 'Tratamientos', 'importable_after_code', 'Depende de riesgo, acción y aprobación; no se inserta fuera de su workflow.'],
  ['standards', 2, 'Normas', 'system_managed', 'El catálogo normativo se administra centralmente.'],
  ['requirements', 2, 'Requisitos', 'system_managed', 'Los requisitos pertenecen a versiones de frameworks administradas por el sistema.'],
  ['mappings', 2, 'Mapeos', 'importable_after_code', 'Requiere revisión tenant y claves estables de ambos extremos.'],
  ['evidences', 2, 'Evidencias', 'security_sensitive', 'El archivo y su metadata deben pasar por carga segura, hash y revisión.'],
  ['findings', 2, 'Hallazgos', 'importable_after_code', 'Debe conservar origen, auditoría y workflow de aprobación.'],
  ['nonconformities', 2, 'No conformidades', 'importable_after_code', 'Debe mantener causa, resolución y evidencias dentro del flujo vigente.'],
  ['actions', 2, 'Acciones', 'importable_after_code', 'Debe preservar responsables, aprobaciones y relaciones GRC.'],
  ['audits', 3, 'Auditorías', 'importable_after_code', 'La planificación requiere equipo, alcance, independencia y programa coherentes.'],
  ['audit_tests', 3, 'Pruebas de auditoría', 'importable_after_code', 'Dependen de un programa y de muestras ya validadas.'],
  ['workpapers', 3, 'Papeles de trabajo', 'security_sensitive', 'Incluyen archivos y revisión de supervisión.'],
  ['privacy_processing', 3, 'Actividades de tratamiento', 'importable_after_code', 'Requiere versionado de privacidad y relaciones de base legal.'],
  ['privacy_dpias', 3, 'DPIA', 'derived', 'Se deriva de actividades y riesgos de privacidad evaluados.'],
  ['privacy_requests', 3, 'Solicitudes de titulares', 'security_sensitive', 'Puede contener datos personales; debe entrar por el flujo protegido.'],
  ['privacy_breaches', 3, 'Brechas de privacidad', 'security_sensitive', 'Requiere gestión de incidente y notificaciones controladas.'],
  ['incidents', 3, 'Incidentes', 'importable_after_code', 'Debe preservar clasificación, cronología y reglas de cierre.'],
  ['supplier_assessments', 3, 'Evaluaciones de proveedores', 'importable_after_code', 'Dependen de proveedor y cuestionario publicado.'],
  ['questionnaires', 3, 'Cuestionarios', 'system_managed', 'Las versiones publicadas son inmutables y administradas.'],
  ['questionnaire_answers', 3, 'Respuestas de cuestionarios', 'security_sensitive', 'Deben ingresar por una sesión de portal autenticada y trazable.'],
];

for (const [entityType, wave, displayName, classification, reason] of blockedDomains) {
  DEFINITIONS.push(blocked({
    entityType,
    wave,
    displayName,
    description: displayName,
    classification,
    reason,
  }));
}

const byEntity = new Map(DEFINITIONS.map(definition => [definition.entityType, Object.freeze(definition)]));

function getImportDefinition(entityType) {
  return byEntity.get(String(entityType || '').trim()) || null;
}

function listImportDefinitions() {
  return DEFINITIONS.map(definition => ({ ...definition }));
}

module.exports = {
  IMPORT_DEFINITION_VERSION: VERSION,
  getImportDefinition,
  listImportDefinitions,
};
