'use strict';

const CATALOG = [
  {
    id: 'customer_support_incidents',
    context: 'Atencion de clientes / incidentes / reclamos',
    keywords: [
      'cliente',
      'clientes',
      'satisfaccion',
      'satisfacción',
      'reclamo',
      'reclamos',
      'incidente',
      'incidentes',
      'soporte',
      'mesa de ayuda',
      'ticket',
      'sla',
    ],
    recommendedEvidence: [
      {
        name: 'Registro de atenciones de mesa de soporte',
        purpose: 'Trazar incidentes, reclamos o solicitudes de clientes desde apertura hasta cierre.',
        recommended_format: [
          'XLSX',
          'CSV exportado de sistema de tickets',
          'PDF generado desde sistema de soporte',
          'Formulario digital',
          'Modulo interno',
        ],
        minimum_fields: [
          'ticket_id',
          'cliente',
          'fecha_apertura',
          'canal',
          'tipo_solicitud',
          'categoria',
          'severidad',
          'responsable',
          'sla_comprometido',
          'estado',
          'accion_realizada',
          'fecha_cierre',
          'resultado',
          'feedback_cliente',
          'causa_raiz_si_aplica',
        ],
        frequency: 'Registro continuo; revision mensual.',
        owner_role: 'Responsable de soporte / atencion al cliente.',
        related_process: 'Atencion de clientes.',
        iso_use: [
          'seguimiento de satisfaccion del cliente',
          'tratamiento de reclamos',
          'control operacional',
          'mejora continua',
        ],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar el registro como XLSX, CSV o PDF consolidado por periodo, indicando responsable, fecha de generacion y fuente del sistema.',
        suggested_action: 'Implementar el registro mensual y cargar los ultimos 3 a 6 meses como evidencia.',
      },
      {
        name: 'Reporte de SLA y reclamos criticos',
        purpose: 'Demostrar seguimiento de tiempos comprometidos, atrasos, reclamos criticos y acciones de recuperacion.',
        recommended_format: ['XLSX', 'Dashboard exportado', 'PDF de reporte mensual'],
        minimum_fields: ['periodo', 'cliente', 'ticket_id', 'sla_comprometido', 'sla_real', 'cumplimiento_sla', 'causa_atraso', 'responsable', 'accion_correctiva'],
        frequency: 'Mensual; revision extraordinaria ante reclamos criticos.',
        owner_role: 'Jefe de soporte o dueno del proceso de atencion de clientes.',
        related_process: 'Atencion de clientes.',
        iso_use: ['desempeno del proceso', 'satisfaccion del cliente', 'mejora continua'],
        evidence_strength: 'secondary',
        maturity_level: 'intermediate',
        how_to_present: 'Presentar reporte mensual con periodo, fuente del sistema, responsable y resumen de excepciones.',
        suggested_action: 'Configurar reporte de SLA mensual y asociar reclamos criticos a acciones o no conformidades cuando corresponda.',
      },
    ],
  },
  {
    id: 'supplier_evaluation',
    context: 'Evaluacion de proveedores',
    keywords: ['proveedor', 'proveedores', 'suministro', 'compras', 'externo', 'outsourcing', 'tercero', 'terceros'],
    recommendedEvidence: [
      {
        name: 'Matriz de evaluacion de proveedores',
        purpose: 'Evidenciar criterios de seleccion, criticidad, desempeno y aprobacion de proveedores relevantes.',
        recommended_format: ['XLSX', 'CSV', 'PDF aprobado', 'Modulo interno'],
        minimum_fields: ['proveedor', 'servicio_producto', 'criticidad', 'criterios', 'puntaje', 'riesgo', 'resultado', 'aprobador', 'fecha_evaluacion', 'proxima_evaluacion'],
        frequency: 'Inicial y reevaluacion anual o ante cambios relevantes.',
        owner_role: 'Responsable de compras / dueno del proceso proveedor.',
        related_process: 'Gestion de proveedores.',
        iso_use: ['control de procesos externos', 'evaluacion de desempeno', 'gestion de riesgos'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar matriz vigente con criterios definidos, aprobador y fecha de proxima revision.',
        suggested_action: 'Clasificar proveedores criticos y completar evaluacion vigente para los proveedores activos.',
      },
    ],
  },
  {
    id: 'document_control',
    context: 'Control documental',
    keywords: ['documento', 'documental', 'version', 'versión', 'aprobacion', 'aprobación', 'procedimiento', 'politica', 'política', 'listado maestro'],
    recommendedEvidence: [
      {
        name: 'Listado maestro de documentos',
        purpose: 'Demostrar control de versiones, responsables, aprobaciones, vigencia y revision documental.',
        recommended_format: ['XLSX', 'CSV', 'PDF controlado', 'Exportacion de gestor documental'],
        minimum_fields: ['codigo', 'nombre', 'version', 'dueno', 'estado', 'fecha_aprobacion', 'fecha_revision', 'proxima_revision', 'aprobador'],
        frequency: 'Actualizacion ante cambios; revision trimestral o semestral.',
        owner_role: 'Responsable de control documental / calidad / cumplimiento.',
        related_process: 'Control documental.',
        iso_use: ['informacion documentada', 'control de cambios', 'trazabilidad de aprobaciones'],
        evidence_strength: 'primary',
        maturity_level: 'basic',
        how_to_present: 'Cargar listado maestro vigente junto con historial o evidencia de aprobacion cuando aplique.',
        suggested_action: 'Consolidar documentos vigentes, duenos y fechas de revision en un listado maestro controlado.',
      },
      {
        name: 'Historial de versiones y aprobaciones',
        purpose: 'Evidenciar cambios, aprobadores y fechas de entrada en vigencia de documentos controlados.',
        recommended_format: ['Registro XLSX', 'Bitacora del gestor documental', 'PDF exportado'],
        minimum_fields: ['codigo', 'documento', 'version_anterior', 'version_nueva', 'cambio_realizado', 'solicitante', 'aprobador', 'fecha_aprobacion'],
        frequency: 'Cada vez que un documento cambie.',
        owner_role: 'Responsable de control documental.',
        related_process: 'Control documental.',
        iso_use: ['control de cambios', 'aprobacion de informacion documentada'],
        evidence_strength: 'secondary',
        maturity_level: 'intermediate',
        how_to_present: 'Adjuntar bitacora de cambios por documento o reporte consolidado del periodo.',
        suggested_action: 'Registrar cambios historicos de documentos criticos y asociarlos al listado maestro.',
      },
    ],
  },
  {
    id: 'training_competence',
    context: 'Capacitacion y competencia',
    keywords: ['capacitacion', 'capacitación', 'competencia', 'competencias', 'formacion', 'formación', 'curso', 'entrenamiento', 'colaborador'],
    recommendedEvidence: [
      {
        name: 'Matriz de competencias',
        purpose: 'Demostrar competencias requeridas, brechas y acciones de formacion por cargo o rol.',
        recommended_format: ['XLSX', 'CSV', 'PDF aprobado', 'Modulo RRHH'],
        minimum_fields: ['colaborador', 'cargo', 'competencia_requerida', 'brecha', 'curso_capacitacion', 'fecha', 'evaluacion', 'resultado', 'evidencia_eficacia'],
        frequency: 'Revision anual y al cambiar cargos, procesos o requisitos.',
        owner_role: 'RRHH / responsable de area.',
        related_process: 'Gestion de competencias.',
        iso_use: ['competencia', 'toma de conciencia', 'eficacia de acciones formativas'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar matriz vigente y respaldos de cursos o evaluaciones de eficacia.',
        suggested_action: 'Identificar brechas por rol critico y asociar plan de formacion con evidencias de eficacia.',
      },
    ],
  },
  {
    id: 'risk_management',
    context: 'Riesgos',
    keywords: ['riesgo', 'riesgos', 'impacto', 'probabilidad', 'tratamiento', 'mitigacion', 'mitigación', 'residual', 'inherente'],
    recommendedEvidence: [
      {
        name: 'Matriz de riesgos',
        purpose: 'Demostrar identificacion, evaluacion, tratamiento, responsables y riesgo residual.',
        recommended_format: ['XLSX', 'CSV', 'PDF aprobado', 'Modulo de riesgos'],
        minimum_fields: ['riesgo', 'causa', 'impacto', 'probabilidad', 'nivel_inherente', 'control_existente', 'tratamiento', 'responsable', 'fecha_objetivo', 'riesgo_residual'],
        frequency: 'Revision trimestral, anual y ante cambios significativos.',
        owner_role: 'Responsable de riesgos / dueno del proceso.',
        related_process: 'Gestion de riesgos.',
        iso_use: ['acciones para abordar riesgos', 'control operacional', 'mejora continua'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar matriz vigente con metodologia, responsable y fecha de revision.',
        suggested_action: 'Actualizar riesgos del proceso y asociar controles o acciones de tratamiento pendientes.',
      },
    ],
  },
  {
    id: 'internal_audit',
    context: 'Auditoria interna',
    keywords: ['auditoria', 'auditoría', 'auditor', 'checklist', 'hallazgo', 'hallazgos', 'programa de auditoria', 'plan de auditoria'],
    recommendedEvidence: [
      {
        name: 'Programa, plan e informe de auditoria interna',
        purpose: 'Evidenciar planificacion, ejecucion, criterio, alcance, hallazgos y seguimiento de auditoria interna.',
        recommended_format: ['PDF firmado', 'DOCX aprobado', 'XLSX de checklist', 'Exportacion de modulo auditoria'],
        minimum_fields: ['fecha', 'alcance', 'criterio', 'auditor', 'auditado', 'hallazgos', 'no_conformidades', 'evidencias_revisadas', 'conclusion', 'seguimiento'],
        frequency: 'Segun programa anual; seguimiento hasta cierre de hallazgos.',
        owner_role: 'Auditor interno / responsable de cumplimiento.',
        related_process: 'Auditoria interna.',
        iso_use: ['evaluacion del desempeno', 'auditoria interna', 'mejora'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar programa anual, plan de auditoria, checklist e informe con seguimiento de acciones.',
        suggested_action: 'Formalizar programa anual y cargar el ultimo informe con hallazgos y estado de acciones.',
      },
    ],
  },
  {
    id: 'nonconformity_corrective_action',
    context: 'No conformidades y acciones correctivas',
    keywords: ['no conformidad', 'no conformidades', 'accion correctiva', 'acción correctiva', 'causa raiz', 'causa raíz', 'correccion', 'corrección', 'eficacia'],
    recommendedEvidence: [
      {
        name: 'Registro de no conformidades y acciones correctivas',
        purpose: 'Trazar incumplimientos, causa raiz, correccion, accion correctiva, cierre y verificacion de eficacia.',
        recommended_format: ['XLSX', 'CSV', 'PDF de modulo de acciones', 'Formulario digital'],
        minimum_fields: ['id_nc', 'descripcion', 'requisito_incumplido', 'causa_raiz', 'correccion_inmediata', 'accion_correctiva', 'responsable', 'fecha_compromiso', 'evidencia_cierre', 'verificacion_eficacia'],
        frequency: 'Registro continuo; revision mensual hasta cierre.',
        owner_role: 'Responsable de cumplimiento / dueno del proceso.',
        related_process: 'Mejora y acciones correctivas.',
        iso_use: ['no conformidad y accion correctiva', 'mejora continua', 'verificacion de eficacia'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar registro vigente con evidencias de cierre y verificacion de eficacia por cada NC.',
        suggested_action: 'Completar causa raiz y evidencia de cierre para NC abiertas o parcialmente tratadas.',
      },
    ],
  },
  {
    id: 'information_security',
    context: 'Seguridad de informacion',
    keywords: ['seguridad', 'informacion', 'información', 'activo', 'activos', 'acceso', 'permisos', 'backup', 'respaldo', 'restauracion', 'restauración', 'incidente de seguridad'],
    recommendedEvidence: [
      {
        name: 'Inventario de activos y control de accesos',
        purpose: 'Demostrar identificacion de activos, responsables, clasificacion y control de permisos.',
        recommended_format: ['XLSX', 'CSV', 'Exportacion IAM', 'PDF de revision de permisos'],
        minimum_fields: ['activo', 'responsable', 'clasificacion', 'riesgo', 'control', 'usuario_rol', 'permiso', 'fecha_revision', 'aprobador'],
        frequency: 'Revision trimestral o ante altas, bajas y cambios de rol.',
        owner_role: 'Responsable de seguridad de informacion / TI.',
        related_process: 'Seguridad de informacion.',
        iso_use: ['gestion de activos', 'control de accesos', 'tratamiento de riesgos de seguridad'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar inventario y evidencia de revision de permisos con periodo y aprobador.',
        suggested_action: 'Consolidar activos criticos y ejecutar revision de accesos para sistemas relevantes.',
      },
      {
        name: 'Registro de incidentes de seguridad y evidencia de backups',
        purpose: 'Demostrar respuesta a incidentes, contencion, investigacion, cierre y capacidad de recuperacion.',
        recommended_format: ['XLSX', 'CSV', 'PDF de ticketing/SIEM', 'Reporte de backup/restauracion'],
        minimum_fields: ['incidente', 'activo', 'impacto', 'contencion', 'investigacion', 'responsable', 'fecha_cierre', 'backup_ejecutado', 'prueba_restauracion', 'resultado'],
        frequency: 'Incidentes en continuo; backups segun politica; pruebas de restauracion al menos periodicas.',
        owner_role: 'TI / seguridad de informacion.',
        related_process: 'Gestion de incidentes y continuidad TI.',
        iso_use: ['gestion de incidentes', 'continuidad operacional', 'control operacional de seguridad'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar reportes por periodo con fuente del sistema, responsable y resultado de pruebas.',
        suggested_action: 'Asociar registros de incidentes, backups y pruebas de restauracion al control correspondiente.',
      },
    ],
  },
  {
    id: 'ai_management_system',
    context: 'IA / ISO 42001',
    keywords: ['ia', 'ai', 'inteligencia artificial', 'modelo', 'dataset', 'datos', 'validacion humana', 'validación humana', 'monitoreo', 'sistema ia'],
    recommendedEvidence: [
      {
        name: 'Inventario de sistemas IA y evaluacion de impacto',
        purpose: 'Demostrar proposito, duenos, datos usados, riesgos, controles, supervision humana y monitoreo de sistemas IA.',
        recommended_format: ['XLSX', 'CSV', 'PDF aprobado', 'Registro GRC/AI governance'],
        minimum_fields: ['sistema_ia', 'proposito', 'dueno', 'datos_usados', 'riesgos', 'controles', 'validacion_humana', 'metricas', 'incidentes', 'revision_periodica'],
        frequency: 'Revision trimestral, ante cambios de modelo/datos y ante incidentes.',
        owner_role: 'Responsable de gobierno IA / dueno del sistema IA.',
        related_process: 'Gobierno de IA.',
        iso_use: ['gobierno de sistemas IA', 'gestion de riesgos IA', 'supervision humana', 'monitoreo'],
        evidence_strength: 'primary',
        maturity_level: 'intermediate',
        how_to_present: 'Cargar inventario vigente y evaluaciones de impacto con responsables, controles y fecha de revision.',
        suggested_action: 'Levantar inventario IA y documentar riesgos, controles y puntos de revision humana para sistemas activos.',
      },
    ],
  },
];

module.exports = {
  CATALOG,
};
