BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE UNIQUE INDEX IF NOT EXISTS ux_knowledge_document_chunks_tenant_chunk_id
  ON knowledge_document_chunks(tenant_id, id);

CREATE TABLE IF NOT EXISTS knowledge_chunk_embeddings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  chunk_id uuid NOT NULL,
  knowledge_document_id uuid NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  document_version text NOT NULL,
  embedding_contract_version text NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  model_version text NOT NULL,
  dimensions integer NOT NULL,
  input_checksum text NOT NULL,
  embedding_checksum text,
  embedding vector,
  status text NOT NULL DEFAULT 'pending',
  failure_code text,
  failure_message text,
  generated_at timestamptz,
  stale_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_chunk_embeddings_chunk_tenant_fkey
    FOREIGN KEY (tenant_id, chunk_id)
    REFERENCES knowledge_document_chunks(tenant_id, id)
    ON DELETE CASCADE,
  CONSTRAINT knowledge_chunk_embeddings_status_check
    CHECK (status IN ('pending','ready','failed','stale','skipped')),
  CONSTRAINT knowledge_chunk_embeddings_dimensions_check
    CHECK (dimensions > 0 AND dimensions <= 4096),
  CONSTRAINT knowledge_chunk_embeddings_input_checksum_check
    CHECK (input_checksum ~ '^[a-f0-9]{64}$'),
  CONSTRAINT knowledge_chunk_embeddings_embedding_checksum_check
    CHECK (embedding_checksum IS NULL OR embedding_checksum ~ '^[a-f0-9]{64}$'),
  CONSTRAINT knowledge_chunk_embeddings_ready_check
    CHECK (
      status <> 'ready'
      OR (embedding IS NOT NULL AND embedding_checksum IS NOT NULL AND generated_at IS NOT NULL)
    ),
  CONSTRAINT knowledge_chunk_embeddings_vector_dimensions_check
    CHECK (embedding IS NULL OR vector_dims(embedding) = dimensions),
  CONSTRAINT knowledge_chunk_embeddings_identity_text_check
    CHECK (
      length(trim(embedding_contract_version)) > 0
      AND length(trim(provider)) > 0
      AND length(trim(model)) > 0
      AND length(trim(model_version)) > 0
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_knowledge_chunk_embeddings_identity
  ON knowledge_chunk_embeddings(
    tenant_id,
    chunk_id,
    embedding_contract_version,
    provider,
    model,
    model_version,
    dimensions,
    input_checksum
  );

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_embeddings_tenant_status
  ON knowledge_chunk_embeddings(
    tenant_id,
    status,
    embedding_contract_version,
    provider,
    model,
    model_version,
    dimensions
  );

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_embeddings_chunk
  ON knowledge_chunk_embeddings(tenant_id, chunk_id, status);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_embeddings_document
  ON knowledge_chunk_embeddings(tenant_id, knowledge_document_id, document_version, status);

COMMENT ON TABLE knowledge_chunk_embeddings IS
  'Embedding-side storage for knowledge-embedding-contract-v1. References canonical knowledge_document_chunks and does not duplicate chunk_text.';

COMMENT ON COLUMN knowledge_chunk_embeddings.embedding IS
  'pgvector value generated by a governed/configured embedding provider. Tenant filtering must happen before vector ranking.';

COMMIT;
