const ERROR_CODES = Object.freeze({
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TENANT_REQUIRED: 'TENANT_REQUIRED',
  LOCALE_UNSUPPORTED: 'LOCALE_UNSUPPORTED',
  REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  AI_REQUEST_FAILED: 'AI_REQUEST_FAILED',
  AI_INSUFFICIENT_CONTEXT: 'AI_INSUFFICIENT_CONTEXT',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  CONTROL_NOT_FOUND: 'CONTROL_NOT_FOUND',
  EVIDENCE_NOT_FOUND: 'EVIDENCE_NOT_FOUND',
  FINDING_NOT_FOUND: 'FINDING_NOT_FOUND',
  ACTION_PLAN_NOT_FOUND: 'ACTION_PLAN_NOT_FOUND',
});

function normalizeErrorCode(code, fallback = ERROR_CODES.SERVER_ERROR) {
  const raw = String(code || '').trim().toUpperCase();

  if (!raw) return fallback;

  return Object.prototype.hasOwnProperty.call(ERROR_CODES, raw)
    ? ERROR_CODES[raw]
    : raw;
}

module.exports = {
  ERROR_CODES,
  normalizeErrorCode,
};
