 'use strict';
const stats = require('./statisticalEngine.service');
const { MathGovernanceError, number } = stats;
const { officialResult, unmeasured } = require('./officialCalculation.service');
const controls = require('./controlCalculation.service');
const risk = require('./riskCalculation.service');
function resultValue(result) { const key = String(result || '').toLowerCase(); if (key === 'pass') return 1; if (key === 'pass_with_observations') return .75; if (key === 'fail') return 0; if (key === 'not_applicable' || key === 'inconclusive') return null; throw new MathGovernanceError('ASSURANCE_INVALID_RESULT', 'Resultado de assurance invalido.'); }
function assuranceScore({ results = [] } = {}) { let weighted = 0, weights = 0, inconclusive = 0, excluded = 0; for (const item of results) { const v = resultValue(item.result); if (v === null) { item.result === 'inconclusive' ? inconclusive++ : excluded++; continue; } const w = number(item.weight ?? 1, 'weight'); weighted += w * v; weights += w; } if (weights === 0) return { status: 'unmeasured', value: null, inconclusive, excluded, usable: 0 }; return { status: 'calculated', value: (weighted / weights) * 100, inconclusive, excluded, usable: weights }; }
function sampleSize(input = {}) { return stats.sampleSize(input); }
function finiteCorrection(input = {}) { return stats.sampleSize(input).adjusted; }
function samplingPlan({ population, confidence = .95, error = .05, p = .5, method = 'random', riskDirected = false } = {}) { const z = confidence >= .99 ? 2.576 : confidence >= .95 ? 1.96 : 1.645; const size = sampleSize({ z, p, e: error, population }); return { method: riskDirected ? 'risk_directed' : method, population, confidence, error, sample_size: Math.ceil(size.adjusted), raw_size: size.n, finite_correction: size.adjusted }; }
function aggregateBy(results = [], key) { const groups = new Map(); for (const item of results) { const group = item[key] || 'unclassified'; groups.set(group, [...(groups.get(group) || []), item]); } return [...groups.entries()].map(([group, rows]) => ({ group, ...assuranceScore({ results: rows }) })); }
function assuranceEffects(input = {}) { const score = assuranceScore(input); const ratio = score.value === null ? null : score.value / 100; return { control_effectiveness: ratio === null ? null : controls.controlEffectiveness({ design: ratio, implementation: ratio, operation: ratio, evidence: ratio }), residual_risk_effect: ratio === null ? null : risk.residualRisk({ inherentRisk: input.inherentRisk ?? 10, controlEffectiveness: ratio }), findings_proposed: score.value !== null && score.value < 70, actions_proposed: score.value !== null && score.value < 85, evidence_required: true, readiness_signal: ratio } }
function officialAssuranceScore(input = {}) { const r = assuranceScore(input); if (r.status !== 'calculated') return unmeasured('F5_5_ASSURANCE_SCORE', 'Assurance sin resultados concluyentes.', { unit: '%', period: input.period || {}, source: input.source || null, warnings: ['inconclusive_not_counted_as_pass'] }); return officialResult('F5_5_ASSURANCE_SCORE', input, { period: input.period || {}, source: input.source || null, coverage: input.coverage ?? null, components: { ...r, by_control: aggregateBy(input.results || [], 'control'), by_risk: aggregateBy(input.results || [], 'risk'), by_process: aggregateBy(input.results || [], 'process'), effects: assuranceEffects(input) }, explanation: 'Assurance Score ponderado; inconclusive no cuenta como aprobado y not_applicable se excluye.' }); }
function officialSampleSize(input = {}) { return officialResult('F5_5_SAMPLE_SIZE', input, { period: input.period || {}, source: input.source || null, components: { plan: samplingPlan(input) } }); }
module.exports = { resultValue, assuranceScore, sampleSize, finiteCorrection, samplingPlan, aggregateBy, assuranceEffects, officialAssuranceScore, officialSampleSize };
