 'use strict';
const { MathGovernanceError, number } = require('./statisticalEngine.service');
const { officialResult, unmeasured, clamp } = require('./officialCalculation.service');
function pct(n, d, code) { const den = number(d, 'denominator'); if (den === 0) throw new MathGovernanceError(code, 'Denominador cero.'); return (number(n, 'numerator') / den) * 100; }
function assertWeights(weights) { const total = Object.values(weights).reduce((s, v) => s + number(v, 'weight'), 0); if (Math.abs(total - 1) > 0.0001) throw new MathGovernanceError('CONTROL_WEIGHTS_SUM_INVALID', 'Pesos de control deben sumar 1.'); }
function combinedEffectiveness({ effectivenesses = [], dependencyFactor = 1 } = {}) { const combined = 1 - effectivenesses.reduce((product, value) => product * (1 - number(value, 'effectiveness')), 1); return clamp(combined * number(dependencyFactor, 'dependencyFactor'), 0, 1); }
function controlEffectiveness({ design, implementation, operation, evidence, weights = { design: 0.25, implementation: 0.25, operation: 0.25, evidence: 0.25 } }) { assertWeights(weights); return clamp(number(weights.design, 'weights.design') * number(design, 'design') + number(weights.implementation, 'weights.implementation') * number(implementation, 'implementation') + number(weights.operation, 'weights.operation') * number(operation, 'operation') + number(weights.evidence, 'weights.evidence') * number(evidence, 'evidence'), 0, 1); }
function controlCoverage({ risksWithControl, relevantRisks }) { return pct(risksWithControl, relevantRisks, 'CONTROL_COVERAGE_ZERO_RELEVANT'); }
function frequencyCompliance({ onTimeExecutions, scheduledExecutions }) { return pct(onTimeExecutions, scheduledExecutions, 'FREQUENCY_ZERO_SCHEDULED'); }
function failureRate({ failedTests, executedTests }) { return pct(failedTests, executedTests, 'FAILURE_ZERO_EXECUTED'); }
function controlsWithoutCurrentEvidence(controls = []) { return controls.filter((control) => control.not_applicable !== true && Number(control.current_evidence_count || control.currentEvidenceCount || 0) <= 0).length; }
function officialControlEffectiveness(input = {}) { return officialResult('F5_5_CONTROL_EFFECTIVENESS', input, { period: input.period || {}, source: input.source || null, coverage: input.coverage ?? null, components: { weights: input.weights || { design: 0.25, implementation: 0.25, operation: 0.25, evidence: 0.25 } }, explanation: 'Efectividad oficial de control con dimensiones visibles D/I/O/E.' }); }
function officialCombinedEffectiveness(input = {}) { if (!input.effectivenesses?.length) return unmeasured('F5_5_COMBINED_EFFECTIVENESS', 'Sin controles relacionados para efectividad combinada.', { unit: 'ratio', period: input.period || {}, source: input.source || null }); return officialResult('F5_5_COMBINED_EFFECTIVENESS', input, { period: input.period || {}, source: input.source || null, components: { dependencyFactor: input.dependencyFactor ?? 1 }, explanation: 'Efectividad combinada oficial como complemento de producto; no suma porcentajes.' }); }
module.exports = { combinedEffectiveness, controlEffectiveness, controlCoverage, frequencyCompliance, failureRate, controlsWithoutCurrentEvidence, officialControlEffectiveness, officialCombinedEffectiveness };
