 'use strict';
const { MathGovernanceError, number } = require('./statisticalEngine.service');
const { officialResult, unmeasured, statusFromScore, clamp } = require('./officialCalculation.service');
const HEALTH_DEFINITIONS = Object.freeze({
  grc_health: { formula_code: 'F5_5_GRC_HEALTH', version: 1, weights: { risk: 0.2, compliance: 0.25, actions: 0.15, evidence: 0.2, dataTrust: 0.2 }, components: ['risk','compliance','actions','evidence','dataTrust'] },
  iso_health: { formula_code: 'F5_5_GRC_HEALTH', version: 1, weights: { risk: 0.15, compliance: 0.3, actions: 0.15, evidence: 0.2, dataTrust: 0.2 }, components: ['risk','compliance','readiness','evidence','actions','dataTrust'] },
  risk_health: { formula_code: 'F5_5_RESIDUAL_RISK', version: 1, weights: { residualRisk: 0.7, dataTrust: 0.3 }, components: ['residualRisk','dataTrust'] },
  control_health: { formula_code: 'F5_5_CONTROL_EFFECTIVENESS', version: 1, weights: { effectiveness: 0.65, coverage: 0.2, dataTrust: 0.15 }, components: ['effectiveness','coverage','dataTrust'] },
  evidence_health: { formula_code: 'F5_5_GRC_HEALTH', version: 1, weights: { evidence: 0.8, dataTrust: 0.2 }, components: ['evidence','dataTrust'] },
  action_health: { formula_code: 'F5_5_WEIGHTED_PROGRESS', version: 1, weights: { progress: 0.6, overdue: 0.25, closure: 0.15 }, components: ['progress','overdue','closure'] },
  data_health: { formula_code: 'F5_5_GRC_HEALTH', version: 1, weights: { dataTrust: 1 }, components: ['dataTrust'] },
  operational_excellence_health: { formula_code: 'F5_5_GRC_HEALTH', version: 1, weights: { risk: 0.15, compliance: 0.15, actions: 0.15, evidence: 0.15, dataTrust: 0.4 }, components: ['efficacy','efficiency','stability','quality','timeliness','risk','compliance','actions','dataTrust'] },
  survey_health: { formula_code: 'F5_5_SURVEY_SCORE', version: 1, weights: { score: 0.55, responseRate: 0.25, consistency: 0.2 }, components: ['score','responseRate','consistency'] },
  assurance_health: { formula_code: 'F5_5_ASSURANCE_SCORE', version: 1, weights: { score: 0.6, evidence: 0.2, sampleQuality: 0.2 }, components: ['score','evidence','sampleQuality'] },
  loss_health: { formula_code: 'F5_5_EXPECTED_LOSS', version: 1, weights: { expectedLoss: 0.45, severity: 0.25, concentration: 0.15, dataTrust: 0.15 }, components: ['expectedLoss','severity','concentration','dataTrust'] },
  continuity_health: { formula_code: 'F5_5_AVAILABILITY', version: 1, weights: { availability: 0.35, sla: 0.25, recovery: 0.25, dataTrust: 0.15 }, components: ['availability','sla','rtoGap','rpoGap','dataTrust'] },
  asset_health: { formula_code: 'F5_5_ASSET_CRITICALITY', version: 1, weights: { classification: 0.5, controlCoverage: 0.25, dataTrust: 0.25 }, components: ['classification','controlCoverage','dataTrust'] },
  supplier_health: { formula_code: 'F5_5_SUPPLIER_RISK', version: 1, weights: { residualRisk: 0.4, assurance: 0.2, continuity: 0.2, losses: 0.1, dataTrust: 0.1 }, components: ['residualRisk','assurance','continuity','losses','dataTrust'] },
});
function assertWeights(weights) { const total = Object.values(weights).reduce((sum, value) => sum + number(value, 'weight'), 0); if (Math.abs(total - 1) > 0.0001) throw new MathGovernanceError('HEALTH_WEIGHTS_SUM_INVALID', 'Pesos de health deben sumar 1.'); }
function inverseResidualRisk(residualRisk, maxRisk = 25) { return clamp(1 - (number(residualRisk, 'residualRisk') / number(maxRisk, 'maxRisk')), 0, 1); }
function grcHealth({ risk, compliance, actions, evidence, dataTrust, weights = HEALTH_DEFINITIONS.grc_health.weights }) { assertWeights(weights); return 100 * (number(weights.risk, 'weights.risk') * number(risk, 'risk') + number(weights.compliance, 'weights.compliance') * number(compliance, 'compliance') + number(weights.actions, 'weights.actions') * number(actions, 'actions') + number(weights.evidence, 'weights.evidence') * number(evidence, 'evidence') + number(weights.dataTrust, 'weights.dataTrust') * number(dataTrust, 'dataTrust')); }
function officialGrcHealth(input = {}) { const missing = ['risk','compliance','actions','evidence','dataTrust'].filter((key) => input[key] === null || input[key] === undefined); if (missing.length) return unmeasured('F5_5_GRC_HEALTH', `Health incompleto: faltan ${missing.join(', ')}.`, { unit: 'score', period: input.period || {}, source: input.source || null }); const result = officialResult('F5_5_GRC_HEALTH', input, { period: input.period || {}, source: input.source || null, coverage: input.coverage ?? null, components: { weights: input.weights || HEALTH_DEFINITIONS.grc_health.weights, values: { risk: input.risk, compliance: input.compliance, actions: input.actions, evidence: input.evidence, dataTrust: input.dataTrust } }, explanation: 'GRC Health oficial con desglose R, C, A, E y Data Trust; componentes faltantes quedan unmeasured.' }); return { ...result, health_status: statusFromScore(result.value) }; }
function officialIsoHealth(input = {}) { return officialGrcHealth({ ...input, weights: HEALTH_DEFINITIONS.iso_health.weights }); }
function listHealthDefinitions() { return Object.entries(HEALTH_DEFINITIONS).map(([score_code, definition]) => ({ score_code, ...definition, status: 'published', period: 'requested_period', coverage: 'explicit', data_trust: 'required', explanation: 'drill_down_required' })); }
module.exports = { HEALTH_DEFINITIONS, listHealthDefinitions, inverseResidualRisk, grcHealth, officialGrcHealth, officialIsoHealth };
