 'use strict';
const stats = require('./statisticalEngine.service');
const risk = require('./riskCalculation.service');
const { MathGovernanceError, number } = stats;
const { officialResult, unmeasured } = require('./officialCalculation.service');
function ensureSingleCurrency(events = []) { const currencies = [...new Set(events.map((e) => e.currency).filter(Boolean))]; if (currencies.length > 1) throw new MathGovernanceError('LOSS_MULTI_CURRENCY', 'No se mezclan monedas sin fuente oficial de tipo de cambio.', { currencies }); return currencies[0] || null; }
function netLoss(input) { return risk.netLoss(input); }
function lossRows(events = []) { return events.map((event) => ({ ...event, netLoss: event.netLoss ?? netLoss({ grossLoss: event.grossLoss ?? event.gross_loss ?? event.gross_loss_amount, recoveries: event.recoveries ?? event.recovery_amount ?? 0 }) })); }
function severityStatistics({ events = [], netLosses = null } = {}) { const values = netLosses || lossRows(events).map((e) => e.netLoss); const clean = stats.numbers(values, { min: 1, label: 'netLosses' }); return { mean: stats.mean(clean), median: stats.median(clean), p75: stats.percentile(clean, .75), p90: stats.percentile(clean, .9), p95: stats.percentile(clean, .95), p99: stats.percentile(clean, .99), stddev: clean.length > 1 ? stats.stddevSample(clean) : 0, mad: stats.mad(clean), max: stats.max(clean), sample_size: clean.length }; }
function frequency({ events = [], periodCount = 1, by = null } = {}) { if (by) { const groups = {}; for (const event of events) groups[event[by] || 'unclassified'] = (groups[event[by] || 'unclassified'] || 0) + 1; return groups; } return events.length / number(periodCount, 'periodCount'); }
function expectedLoss(input = {}) { if (input.expectedFrequency !== undefined) return risk.expectedLoss(input); const sev = severityStatistics(input); return risk.expectedLoss({ expectedFrequency: frequency(input), meanSeverity: sev.mean }); }
function parametricVaR(input = {}) { const sample = input.netLosses || lossRows(input.events || []).map((e) => e.netLoss); if (sample.length < (input.minimumSample || 5)) throw new MathGovernanceError('VAR_SAMPLE_TOO_SMALL', 'VaR requiere muestra suficiente.'); const sigma = input.sigma ?? stats.stddevSample(sample); if (sigma === 0) throw new MathGovernanceError('VAR_ZERO_SIGMA', 'VaR requiere desviacion positiva.'); return risk.parametricVaR({ mean: input.mean ?? stats.mean(sample), sigma, z: input.z ?? 1.65 }); }
function monteCarlo(input = {}) { if (!input.seed && input.seed !== 0) throw new MathGovernanceError('MONTE_CARLO_SEED_REQUIRED', 'Monte Carlo requiere semilla reproducible.'); return stats.monteCarlo(input); }
function exceedanceProbability(simulation, threshold) { return simulation.exceedanceProbability ?? 0; }
function concentration({ events = [], by = 'process' } = {}) { const rows = lossRows(events); const total = rows.reduce((s, e) => s + number(e.netLoss, 'netLoss'), 0); const groups = {}; for (const e of rows) groups[e[by] || 'unclassified'] = (groups[e[by] || 'unclassified'] || 0) + e.netLoss; return Object.entries(groups).map(([group, value]) => ({ group, value, share: total ? value / total : null })).sort((a,b)=>b.value-a.value); }
function officialNetLoss(input = {}) { return officialResult('F5_5_NET_LOSS', input, { period: input.period || {}, source: input.source || null, components: { currency: input.currency || null } }); }
function officialExpectedLoss(input = {}) { const value = expectedLoss(input); return officialResult('F5_5_EXPECTED_LOSS', { expectedFrequency: input.expectedFrequency ?? frequency(input), meanSeverity: input.meanSeverity ?? severityStatistics(input).mean }, { period: input.period || {}, source: input.source || null, components: { method: 'frequency_mean_severity', currency: ensureSingleCurrency(input.events || []) }, explanation: 'Expected Loss oficial por frecuencia y severidad media; monedas separadas.' }); }
function officialSeverity(input = {}) { const r = severityStatistics(input); return officialResult('F5_5_LOSS_SEVERITY', { netLosses: input.netLosses || lossRows(input.events || []).map(e=>e.netLoss) }, { period: input.period || {}, source: input.source || null, components: r }); }
function officialVaR(input = {}) { const value = parametricVaR(input); return officialResult('F5_5_PARAMETRIC_VAR', { mean: input.mean ?? severityStatistics(input).mean, z: input.z ?? 1.65, sigma: input.sigma ?? stats.stddevSample(input.netLosses || lossRows(input.events || []).map(e=>e.netLoss)) }, { period: input.period || {}, source: input.source || null, components: { assumptions: 'normal_parametric', sample_size: (input.netLosses || input.events || []).length, value } }); }
function officialMonteCarlo(input = {}) { const r = monteCarlo(input); return officialResult('F5_5_MONTE_CARLO', input, { period: input.period || {}, source: input.source || null, components: r, explanation: 'Monte Carlo oficial reproducible con semilla, frecuencia Poisson y severidad configurada.' }); }
module.exports = { ensureSingleCurrency, netLoss, lossRows, severityStatistics, frequency, expectedLoss, parametricVaR, monteCarlo, exceedanceProbability, concentration, officialNetLoss, officialExpectedLoss, officialSeverity, officialVaR, officialMonteCarlo };
