 'use strict';
const assert = require('assert');
const survey = require('./surveyCalculation.service');
const assurance = require('./assuranceCalculation.service');
const loss = require('./lossCalculation.service');
const continuity = require('./continuityCalculation.service');
const asset = require('./assetCalculation.service');
const supplier = require('./supplierCalculation.service');
const phase = require('./phase5Package3.service');
const jobs = require('./phase5Package4Jobs.service');
function close(actual, expected, tolerance = 0.0001) { assert.ok(Math.abs(actual - expected) <= tolerance, `${actual} != ${expected}`); }
let assertions = 0; function check(fn) { fn(); assertions += 1; }
const tenantA = '70000000-0000-0000-0000-000000000701'; const tenantB = '70000000-0000-0000-0000-000000000702';
const surveyItems = [
  { score: 4, maxScore: 5, weight: 2, section: 's1', dimension: 'd1' },
  { score: 3, maxScore: 5, weight: 1, section: 's1', dimension: 'd1' },
  { score: 2, maxScore: 4, weight: 1, section: 's2', dimension: 'd2', visible: false },
  { score: 1, maxScore: 5, weight: 1, section: 's2', dimension: 'd2', notApplicable: true },
  { score: null, maxScore: 5, weight: 1, section: 's2', dimension: 'd2' },
];
check(()=>close(survey.surveyScore({ items: surveyItems }).value, 73.3333333333));
check(()=>assert.equal(survey.surveyScore({ items: surveyItems }).expected, 3));
check(()=>assert.equal(survey.surveyScore({ items: surveyItems }).usable, 2));
check(()=>assert.equal(survey.groupScore(surveyItems, 'section').length, 2));
check(()=>assert.equal(survey.groupScore(surveyItems, 'dimension').find(x=>x.group==='d1').status, 'calculated'));
check(()=>close(survey.responseRate({ completedResponses: 8, validInvitations: 10 }), 80));
check(()=>close(survey.dropoutRate({ started: 10, completed: 7 }), 30));
check(()=>close(survey.cronbach({ matrix: [[1,2,3],[2,3,4],[3,4,5],[4,5,6]] }).value, 1));
check(()=>assert.equal(survey.cronbach({ matrix: [[1],[2]], compatible: true }).status, 'not_applicable'));
check(()=>assert.equal(survey.cronbach({ matrix: [[1,2]], minimumSample: 2 }).status, 'unmeasured'));
check(()=>assert.equal(survey.officialSurveyScore({ items: surveyItems }).formula_code, 'F5_5_SURVEY_SCORE'));
check(()=>assert.ok(survey.officialSurveyScore({ items: surveyItems }).trust_score >= 0));
check(()=>assert.equal(survey.campaignAnalytics({ items: surveyItems, completedResponses: 8, validInvitations: 10, started: 10, completed: 7 }).response_rate, 80));
check(()=>assert.ok(survey.grcProposals({ score: 45, responseRate: 60, supplierId: 's1' }).every(x=>x.requires_approval)));
check(()=>assert.equal(survey.officialCronbach({ matrix: [[1,2,3],[2,3,4],[3,4,5],[4,5,6]] }).formula_code, 'F5_5_CRONBACH_ALPHA'));
check(()=>assert.equal(assurance.resultValue('pass'), 1));
check(()=>assert.equal(assurance.resultValue('pass_with_observations'), .75));
check(()=>assert.equal(assurance.resultValue('fail'), 0));
check(()=>assert.equal(assurance.resultValue('inconclusive'), null));
check(()=>assert.equal(assurance.resultValue('not_applicable'), null));
const assuranceResults = [{ result:'pass', weight:2, control:'c1', risk:'r1', process:'p1' },{ result:'pass_with_observations', weight:1, control:'c1', risk:'r1', process:'p1' },{ result:'fail', weight:1, control:'c2', risk:'r2', process:'p2' },{ result:'inconclusive', weight:1, control:'c2' }];
check(()=>close(assurance.assuranceScore({ results: assuranceResults }).value, 68.75));
check(()=>assert.ok(assurance.sampleSize({ z:1.96,p:.5,e:.05 }).n > 300));
check(()=>assert.ok(assurance.finiteCorrection({ z:1.96,p:.5,e:.05,population:1000 }) < assurance.sampleSize({ z:1.96,p:.5,e:.05 }).n));
check(()=>assert.equal(assurance.aggregateBy(assuranceResults, 'control').length, 2));
check(()=>assert.equal(assurance.assuranceEffects({ results: assuranceResults }).findings_proposed, true));
check(()=>assert.equal(assurance.officialAssuranceScore({ results: assuranceResults }).formula_code, 'F5_5_ASSURANCE_SCORE'));
check(()=>assert.equal(assurance.officialSampleSize({ z:1.96,p:.5,e:.05,population:1000 }).formula_code, 'F5_5_SAMPLE_SIZE'));
check(()=>assert.ok(assurance.samplingPlan({ population:100, riskDirected:true }).method === 'risk_directed'));
const events = [{ grossLoss:1000, recoveries:250, currency:'CLP', process:'p1', supplier:'s1' },{ grossLoss:500, recoveries:100, currency:'CLP', process:'p1', supplier:'s2' },{ grossLoss:1500, recoveries:0, currency:'CLP', process:'p2', supplier:'s1' },{ grossLoss:2000, recoveries:500, currency:'CLP', process:'p2', supplier:'s1' },{ grossLoss:800, recoveries:300, currency:'CLP', process:'p3', supplier:'s2' }];
check(()=>assert.equal(loss.netLoss({ grossLoss:1000, recoveries:250 }), 750));
check(()=>assert.throws(()=>loss.netLoss({ grossLoss:100, recoveries:200 }), /neta/));
check(()=>assert.equal(loss.lossRows(events)[0].netLoss, 750));
check(()=>assert.ok(loss.expectedLoss({ events, periodCount: 1 }) > 0));
check(()=>assert.ok(loss.severityStatistics({ events }).mean > 0));
check(()=>assert.ok(loss.severityStatistics({ events }).median > 0));
check(()=>assert.ok(loss.severityStatistics({ events }).p95 >= loss.severityStatistics({ events }).p75));
check(()=>assert.ok(loss.parametricVaR({ events, minimumSample:5 }) > 0));
check(()=>assert.throws(()=>loss.parametricVaR({ events:[events[0]], minimumSample:5 }), /muestra/));
const mc1 = loss.monteCarlo({ iterations:200, seed:42, frequency:{type:'poisson',lambda:1}, severity:{type:'fixed',value:100}, threshold:200 });
const mc2 = loss.monteCarlo({ iterations:200, seed:42, frequency:{type:'poisson',lambda:1}, severity:{type:'fixed',value:100}, threshold:200 });
check(()=>close(mc1.expectedValue, mc2.expectedValue));
check(()=>assert.ok(loss.exceedanceProbability(mc1, 200) >= 0));
check(()=>assert.throws(()=>loss.ensureSingleCurrency([...events, { grossLoss:1, recoveries:0, currency:'USD' }]), /monedas/));
check(()=>assert.equal(loss.concentration({ events, by:'process' })[0].group, 'p2'));
check(()=>assert.equal(loss.officialExpectedLoss({ events, periodCount:1 }).formula_code, 'F5_5_EXPECTED_LOSS'));
check(()=>assert.equal(loss.officialMonteCarlo({ iterations:100, seed:7, frequency:{type:'poisson',lambda:1}, severity:{type:'fixed',value:10}, threshold:20 }).formula_code, 'F5_5_MONTE_CARLO'));
check(()=>close(continuity.availability({ totalTime:1000, downtime:10 }), 99));
check(()=>close(continuity.availability({ mtbf:250, mttr:5 }), 98.039215686, .0001));
check(()=>close(continuity.mtbf({ operatingTime:1000, failures:4 }), 250));
check(()=>close(continuity.mttr({ repairTimes:[2,4,6] }), 4));
check(()=>close(continuity.slaCompliance({ withinSla:45, applicableCases:50 }), 90));
check(()=>assert.equal(continuity.rtoGap({ recoveryActual:6, rtoObjective:4 }), 2));
check(()=>assert.equal(continuity.rpoGap({ dataLossActual:3, rpoObjective:1 }), 2));
check(()=>assert.ok(continuity.continuityHealth({ availabilityScore:99, slaScore:90, testScore:80, actionScore:70, trustScore:90 }) > 80));
check(()=>assert.equal(continuity.officialAvailability({ totalTime:1000, downtime:10 }).formula_code, 'F5_5_AVAILABILITY'));
check(()=>assert.equal(continuity.officialRtoGap({ recoveryActual:6, rtoObjective:4 }).unit, 'hours'));
check(()=>assert.ok(asset.assetCriticality({ confidentiality:4, integrity:5, availability:3, legal:2 }).value > 50));
check(()=>assert.throws(()=>asset.assetCriticality({ confidentiality:4, integrity:5, availability:3, legal:2, weights:{ confidentiality:.5, integrity:.5, availability:.5, legal:.5 } }), /Pesos/));
check(()=>assert.ok(asset.assetCriticality({ confidentiality:1, integrity:5, availability:3, legal:2 }).components.integrity === 1));
check(()=>assert.equal(asset.classify(85), 'critical'));
check(()=>assert.equal(asset.officialAssetCriticality({ confidentiality:4, integrity:5, availability:3, legal:2 }).formula_code, 'F5_5_ASSET_CRITICALITY'));
check(()=>assert.ok(supplier.inherentRisk({ criticality:4, security:3, dependency:5, performance:2, resilience:1 }) > 0));
check(()=>assert.ok(supplier.residualRisk({ criticality:4, security:3, dependency:5, performance:2, resilience:1, controlEffectiveness:.5 }) <= supplier.inherentRisk({ criticality:4, security:3, dependency:5, performance:2, resilience:1 })));
check(()=>assert.ok(supplier.health({ criticality:4, security:3, dependency:5, performance:2, resilience:1, controlEffectiveness:.5, surveyScore:80, assuranceScore:70, continuityScore:90, lossScore:60 }) !== null));
check(()=>assert.equal(supplier.trend([1,2,3]).direction, 'increase'));
check(()=>assert.equal(supplier.concentration([{id:'s1',exposure:100},{id:'s2',exposure:50}])[0].supplier_id, 's1'));
check(()=>assert.equal(supplier.officialSupplierRisk({ criticality:4, security:3, dependency:5, performance:2, resilience:1 }).formula_code, 'F5_5_SUPPLIER_RISK'));
check(()=>assert.equal(phase.calculateOfficialByKey('survey-score', { items: surveyItems }).formula_code, 'F5_5_SURVEY_SCORE'));
check(()=>assert.equal(phase.calculateOfficialByKey('assurance-score', { results: assuranceResults }).formula_code, 'F5_5_ASSURANCE_SCORE'));
check(()=>assert.equal(phase.calculateOfficialByKey('loss-net', { grossLoss:1000, recoveries:250 }).formula_code, 'F5_5_NET_LOSS'));
check(()=>assert.equal(phase.calculateOfficialByKey('continuity-sla', { withinSla:9, applicableCases:10 }).formula_code, 'F5_5_SLA_COMPLIANCE'));
check(()=>assert.equal(phase.calculateOfficialByKey('asset-criticality', { confidentiality:4, integrity:5, availability:3, legal:2 }).formula_code, 'F5_5_ASSET_CRITICALITY'));
check(()=>assert.equal(phase.calculateOfficialByKey('supplier-risk', { criticality:4, security:3, dependency:5, performance:2, resilience:1 }).formula_code, 'F5_5_SUPPLIER_RISK'));
const jobA = jobs.runPackage4Job({ tenantId: tenantA, jobKey:'survey.calculate', input:{ items: surveyItems } });
const jobB = jobs.runPackage4Job({ tenantId: tenantA, jobKey:'survey.calculate', input:{ items: surveyItems } });
check(()=>assert.equal(jobA.idempotency_key, jobB.idempotency_key));
check(()=>assert.notEqual(jobs.runPackage4Job({ tenantId: tenantB, jobKey:'survey.calculate', input:{ items: surveyItems } }).idempotency_key, jobA.idempotency_key));
check(()=>assert.equal(jobs.listPackage4Jobs().length, 9));
check(()=>assert.throws(()=>jobs.runPackage4Job({ tenantId: tenantA, jobKey:'unknown', input:{} }), /no soportado/));
check(()=>assert.equal(jobA.snapshot.formula_code, 'F5_5_SURVEY_SCORE'));
check(()=>assert.ok(jobA.idempotency_key.length === 64));
check(()=>assert.ok(jobA.result.explanation_url.includes('/api/grc/official/calculations/')));
check(()=>assert.ok(jobA.result.lineage_url.includes('/api/grc/official/calculations/')));
check(()=>assert.equal(phase.calculateOfficialByKey('loss-monte-carlo', { iterations:100, seed:99, frequency:{type:'poisson',lambda:1}, severity:{type:'fixed',value:100}, threshold:200 }).formula_code, 'F5_5_MONTE_CARLO'));
check(()=>assert.equal(supplier.residualRisk({ inherent:10, controlEffectiveness:.25 }) <= 10, true));
console.log(JSON.stringify({ status:'PHASE5_5_PACKAGE4_TESTS_OK', assertions }));
