 'use strict';
const { MathGovernanceError, number } = require('./statisticalEngine.service');
const { officialResult, unmeasured, clamp } = require('./officialCalculation.service');
function assertWeights(weights) { const total = Object.values(weights).reduce((sum, value) => sum + number(value, 'weight'), 0); if (Math.abs(total - 1) > 0.0001) throw new MathGovernanceError('READINESS_WEIGHTS_SUM_INVALID', 'Pesos de readiness deben sumar 1.'); }
function weightedComponents(components, weights) { assertWeights(weights); return Object.keys(weights).reduce((total, key) => total + number(weights[key], `weights.${key}`) * number(components[key], `components.${key}`), 0); }
function readiness({ compliance, evidence, health, actions, coverage = 100, weights = { compliance: 0.35, evidence: 0.25, health: 0.25, actions: 0.15 }, minimumCoverage = 70 }) { const raw = 100 * weightedComponents({ compliance, evidence, health, actions }, weights); const penalty = Number(coverage) < minimumCoverage ? Number(coverage) / minimumCoverage : 1; return clamp(raw * penalty, 0, 100); }
function officialReadiness(input = {}) { if ([input.compliance, input.evidence, input.health, input.actions].some((value) => value === null || value === undefined)) return unmeasured('F5_5_READINESS', 'Readiness incompleto: faltan componentes oficiales.', { unit: 'score', period: input.period || {}, source: input.source || null }); const value = readiness(input); return officialResult('F5_5_READINESS', input, { period: input.period || {}, source: input.source || null, coverage: input.coverage ?? null, components: { weights: input.weights || { compliance: 0.35, evidence: 0.25, health: 0.25, actions: 0.15 }, coverage_penalty_applied: Number(input.coverage ?? 100) < Number(input.minimumCoverage ?? 70), value }, explanation: 'Readiness oficial ponderado con penalizacion explicita por cobertura insuficiente. No afirma certificacion.' }); }
function maturity({ levels = [] }) { let weighted = 0, weights = 0; for (const item of levels) { weighted += number(item.level, 'level') * number(item.weight ?? 1, 'weight'); weights += number(item.weight ?? 1, 'weight'); } return weights === 0 ? null : weighted / weights; }
module.exports = { readiness, officialReadiness, maturity };
