 'use strict';
const { MathGovernanceError, number, mean, percentile, monteCarlo } = require('./statisticalEngine.service');
const { officialResult, unmeasured, clamp } = require('./officialCalculation.service');
function inherentRisk({ probability, impact }) { return number(probability, 'probability') * number(impact, 'impact'); }
function residualRisk({ inherentRisk: ri, controlEffectiveness }) { return number(ri, 'inherentRisk') * (1 - number(controlEffectiveness, 'controlEffectiveness')); }
function expectedLoss(input) { if (input.probability !== undefined && input.probability !== null) return number(input.probability, 'probability') * number(input.impact, 'impact'); if (input.expectedFrequency !== undefined && input.expectedFrequency !== null) return number(input.expectedFrequency, 'expectedFrequency') * number(input.meanSeverity, 'meanSeverity'); throw new MathGovernanceError('EXPECTED_LOSS_METHOD_REQUIRED', 'Expected loss requiere probabilidad/impacto o frecuencia/severidad.'); }
function netLoss({ grossLoss, recoveries = 0 }) { const value = number(grossLoss, 'grossLoss') - number(recoveries, 'recoveries'); if (value < 0) throw new MathGovernanceError('NET_LOSS_NEGATIVE', 'La perdida neta no puede ser negativa.'); return value; }
function lossSeverity({ netLosses = [] }) { return { value: mean(netLosses), median: percentile(netLosses, 0.5), p90: percentile(netLosses, 0.9), p95: percentile(netLosses, 0.95), p99: percentile(netLosses, 0.99) }; }
function parametricVaR({ mean: mu, z, sigma }) { return number(mu, 'mean') + number(z, 'z') * number(sigma, 'sigma'); }
function fmeaRpn({ severity, occurrence, detection }) { return number(severity, 'severity') * number(occurrence, 'occurrence') * number(detection, 'detection'); }
function normalizeScale(value, { min = 1, max = 5, inverse = false } = {}) { const normalized = (number(value, 'value') - min) / (max - min); return clamp(inverse ? 1 - normalized : normalized, 0, 1); }
function classifyRisk(value, thresholds = { low: 4, medium: 9, high: 15 }) { const score = number(value, 'riskValue'); if (score >= thresholds.high) return 'critical'; if (score >= thresholds.medium) return 'high'; if (score >= thresholds.low) return 'medium'; return 'low'; }
function multidimensionalImpact(dimensions = {}, weights = {}) { const keys = Object.keys(dimensions); if (!keys.length) throw new MathGovernanceError('RISK_IMPACT_REQUIRED', 'Impacto multidimensional requiere dimensiones.'); const normalizedWeights = keys.reduce((acc, key) => ({ ...acc, [key]: weights[key] ?? 1 / keys.length }), {}); const total = Object.values(normalizedWeights).reduce((sum, value) => sum + number(value, 'weight'), 0); if (Math.abs(total - 1) > 0.0001) throw new MathGovernanceError('RISK_WEIGHTS_SUM_INVALID', 'Pesos de impacto deben sumar 1.'); return keys.reduce((sum, key) => sum + number(dimensions[key], key) * number(normalizedWeights[key], `weights.${key}`), 0); }
function officialInherentRisk(input = {}) { return officialResult('F5_5_INHERENT_RISK', input, { period: input.period || {}, source: input.source || null, components: { method: input.method || 'matrix', scale: input.scale || '5x5' }, explanation: 'Riesgo inherente oficial como probabilidad por impacto normalizado.' }); }
function officialResidualRisk(input = {}) { return officialResult('F5_5_RESIDUAL_RISK', input, { period: input.period || {}, source: input.source || null, components: { method: input.method || 'matrix', controlEffectiveness: input.controlEffectiveness }, explanation: 'Riesgo residual oficial ajustado por efectividad de control.' }); }
function officialExpectedLoss(input = {}) { if (input.probability === undefined && input.expectedFrequency === undefined) return unmeasured('F5_5_EXPECTED_LOSS', 'No hay frecuencia/probabilidad para perdida esperada.', { unit: 'currency', period: input.period || {}, source: input.source || null }); return officialResult('F5_5_EXPECTED_LOSS', input, { period: input.period || {}, source: input.source || null, components: { method: input.expectedFrequency !== undefined ? 'frequency_severity' : 'probability_impact' } }); }
function assetCriticality({ confidentiality, integrity, availability, legal, weights = { confidentiality: 0.25, integrity: 0.25, availability: 0.25, legal: 0.25 } }) { return number(weights.confidentiality, 'weights.confidentiality') * number(confidentiality, 'confidentiality') + number(weights.integrity, 'weights.integrity') * number(integrity, 'integrity') + number(weights.availability, 'weights.availability') * number(availability, 'availability') + number(weights.legal, 'weights.legal') * number(legal, 'legal'); }
function supplierRisk({ compliance, security, dependency, privacy, resilience, weights = { compliance: 0.2, security: 0.2, dependency: 0.2, privacy: 0.2, resilience: 0.2 } }) { return number(weights.compliance, 'weights.compliance') * number(compliance, 'compliance') + number(weights.security, 'weights.security') * number(security, 'security') + number(weights.dependency, 'weights.dependency') * number(dependency, 'dependency') + number(weights.privacy, 'weights.privacy') * number(privacy, 'privacy') + number(weights.resilience, 'weights.resilience') * number(resilience, 'resilience'); }
module.exports = { inherentRisk, residualRisk, expectedLoss, netLoss, lossSeverity, parametricVaR, monteCarlo, fmeaRpn, normalizeScale, classifyRisk, multidimensionalImpact, officialInherentRisk, officialResidualRisk, officialExpectedLoss, assetCriticality, supplierRisk };
