 'use strict';
const { MathGovernanceError, number, linearRegression } = require('./statisticalEngine.service');
const { officialResult, clamp } = require('./officialCalculation.service');
const risk = require('./riskCalculation.service');
function assertWeights(weights) { const total = Object.values(weights).reduce((s,v)=>s+number(v,'weight'),0); if (Math.abs(total-1)>.0001) throw new MathGovernanceError('SUPPLIER_WEIGHTS_SUM_INVALID','Pesos de proveedor deben sumar 1.'); }
function supplierRisk({ criticality, compliance, security, dependency, performance, resilience, weights = { criticality:.2, security:.25, dependency:.2, performance:.15, resilience:.2 } } = {}) { assertWeights(weights); const values = { criticality, security, dependency, performance: performance ?? compliance, resilience }; return Object.entries(weights).reduce((s,[k,w])=>s+w*number(values[k],k),0); }
function inherentRisk(input={}) { return supplierRisk(input); }
function residualRisk(input={}) { const inherent = input.inherent ?? inherentRisk(input); const controls = number(input.contractualControls ?? input.controlEffectiveness ?? 0,'controlEffectiveness'); return clamp(inherent*(1-controls),0,100); }
function health(input={}) { const residual = residualRisk(input); const survey = input.surveyScore ?? null, assurance = input.assuranceScore ?? null, continuity = input.continuityScore ?? null, loss = input.lossScore ?? null; const values = [100-residual, survey, assurance, continuity, loss].filter(v=>v!==null&&v!==undefined); return values.length ? values.reduce((s,v)=>s+number(v,'component'),0)/values.length : null; }
function trend(values=[]) { if (values.length < 2) return { direction: 'insufficient_data', slope: null }; return linearRegression(values.map((y,i)=>({x:i,y}))); }
function concentration(suppliers=[]) { const total = suppliers.reduce((s,x)=>s+number(x.exposure ?? x.value ?? 0,'exposure'),0); return suppliers.map(s=>({ supplier_id: s.id || s.supplier_id, exposure: number(s.exposure ?? s.value ?? 0,'exposure'), share: total ? number(s.exposure ?? s.value ?? 0,'exposure')/total : null })).sort((a,b)=>b.exposure-a.exposure); }
function officialSupplierRisk(input={}) { return officialResult('F5_5_SUPPLIER_RISK', { compliance: input.criticality ?? input.compliance, security: input.security, dependency: input.dependency, privacy: input.performance ?? input.privacy ?? input.compliance, resilience: input.resilience }, { period: input.period||{}, source: input.source||null, components: { inherent: inherentRisk(input), residual: residualRisk(input), health: health(input), trend: input.trendValues ? trend(input.trendValues) : null, concentration: input.suppliers ? concentration(input.suppliers) : null, integrations: { surveys: input.surveyScore ?? null, assurance: input.assuranceScore ?? null, losses: input.lossScore ?? null, continuity: input.continuityScore ?? null } }, explanation: 'Riesgo oficial de proveedor con criticidad, seguridad, dependencia, desempeño y resiliencia.' }); }
module.exports = { supplierRisk, inherentRisk, residualRisk, health, trend, concentration, officialSupplierRisk };
